### ISSUE TITLE
[ksp] java.lang.IllegalArgumentException: this and base files have different roots

### ISSUE THREAD

**Issue by mtrakal** [google/ksp#1079]
KSP didn't respect gradle `buildDir` variable.

Using RAM disk for build fodlers:

**USER_HOME/.gradle/init.gradle**
```
allprojects {
    buildDir="Z:/build/$group/$name/"
}
```

**app/build.gradle**
```
android {
    sourceSets {
        androidTest.assets.srcDirs += files("$projectDir/schemas".toString())

        main.kotlin.srcDirs += '$buildDir/generated/ksp/$name/kotlin/'
        test.kotlin.srcDirs += '$buildDir/generated/ksp/$name/kotlin/'
    }

    buildTypes {
       // https://github.com/InsertKoinIO/koin-annotations
        applicationVariants.all { variant ->
            variant.sourceSets.java.each {
                it.srcDirs += "$buildDir/generated/ksp/${variant.name}/kotlin/"
            }
        }
   }
}
```

But build failed with:

```
e: [ksp] java.lang.IllegalArgumentException: this and base files have different roots: Z:\build\ProjectX\app\generated\ksp\stagingDebug\java\cz\packagename\data\database\dao\UserOauthDao_Impl.java and D:\Projects\company\ProjectX\app.
	at kotlin.io.FilesKt__UtilsKt.toRelativeString(Utils.kt:117)
	at kotlin.io.FilesKt__UtilsKt.relativeTo(Utils.kt:128)
	at com.google.devtools.ksp.processing.impl.CodeGeneratorImpl.associate(CodeGeneratorImpl.kt:119)
	at com.google.devtools.ksp.processing.impl.CodeGeneratorImpl.createNewFile(CodeGeneratorImpl.kt:92)
	at androidx.room.compiler.processing.ksp.KspFiler.createNewFile(KspFiler.kt:106)
	at androidx.room.compiler.processing.ksp.KspFiler.write(KspFiler.kt:41)
	at androidx.room.compiler.processing.XFilerKt.writeTo(XFiler.kt:44)
	at androidx.room.compiler.processing.XFilerKt.writeTo$default(XFiler.kt:43)
	at androidx.room.writer.ClassWriter.write(ClassWriter.kt:75)
	at androidx.room.DatabaseProcessingStep.process(DatabaseProcessingStep.kt:111)
	at androidx.room.DatabaseProcessingStep.process(DatabaseProcessingStep.kt:42)
```

**Comment by changfeng1050** [comment]
I have come across this problem too. And found no method to solve it.  So I have to continue to use kapt.  I prefer to use ramdisk other then ksp.

**Comment by xBlackCat** [comment]
Any progress on the issue?

**Comment by mtrakal** [comment]
@neetopia could you please, set new milestone? 1.0.9 was already released (with only 56% complete) and this was not fixed... Still valid.

**Comment by SysoenkovDmitry** [comment]
Change projects to use same drives (root path).
For example **D:\Projects**\company and **D:\Projects**\build\ProjectX

**Comment by xBlackCat** [comment]
@SysoenkovDmitry , your suggestion is completely ruined idea of using RAM disk or other possible configurations of gradle. Also, since KSP 2.0 it is not allowed to have gradle data cache folder and project folder on different drives. If gradle annd its data folder are located on drive D: and project is on drive P: the configuration also causing the same exception "with different roots"

Gradle configuration could be very flexible and KSP plugin totally disallow to use any flexibility provided by gradle.

Could it possible to use FilesKt__UtilsKt.toRelativeString method with fallback to absolute path if relative could not be calculated?

**Comment by est7** [comment]
Many Windows users face an issue where their Gradle path doesn't match their project path.This issue should be looked at

**Comment by xBlackCat** [comment]
Any progress on the three-years-old issue?

**Comment by ExOLiNe** [comment]
Any progress?

**Comment by dmdg0** [comment]
Same issue here, any udates?

**Comment by SysoenkovDmitry** [comment]
The error message "this and base files have different roots" typically occurs in development environments like Flutter and Android Studio when project-related files and their dependencies (e.g., a package cache) are located on different file system drives. This conflict arises during the build process, often due to strict file path validation by tools like Gradle or KSP (Kotlin Symbol Processing). 

The Cause of the Error
This issue commonly happens when:
Your main project is on one drive (e.g., D:\workspace\myapp).
A dependency, such as a Flutter PUB_CACHE or a Gradle cache, is on a different drive (e.g., C:\Users\...\AppData\Local\Pub\Cache). 

Gradle's build process, in certain configurations, requires all related files to share the same base root directory (drive) for path normalization and validation. 

Common Solutions
The most effective and widely recommended solution involves moving the cache directory to the same drive as your project and updating the environment variables to reflect this change. 

Step-by-step fix (for Windows/Flutter):
Move the cache folder: Create a new folder on the same drive as your project (e.g., D:\PubCache).
Move contents: Move the contents of your existing Pub\Cache folder (usually located at C:\Users\<YOURNAME>\AppData\Local\Pub\Cache) to the new location (e.g., D:\PubCache).
Set an Environment Variable:
Open System Properties (search for "Environment Variables" in the Start menu).
Under "User variables", click "New".
Set Variable Name to PUB_CACHE.
Set Variable Value to the path of your new cache folder (e.g., D:\PubCache).
Restart: Close and restart your IDE (Android Studio, VS Code, etc.) and any open terminals for the changes to take effect.
Clean and Re-get packages: In your project's terminal, run the following commands:
flutter clean
flutter pub get
Optionally, run flutter pub cache repair. 

Other potential workarounds that might help (but often the environment variable fix is required):
Run flutter clean and sync Gradle files.
Invalidate caches and restart the IDE (File > Invalidate Caches/Restart).
Ensure all plugins and the Flutter environment are up to date and compatible.

**Comment by axoking** [comment]
@SysoenkovDmitry it shouldn't be like that. Gradle build my app fine when the build directory is on a different drive, except for KSP, which falls. The error message is printed by KSP (with the e: prefix). No flutter / android involved

**Comment by SysoenkovDmitry** [comment]
@axoking 
KSP 2.0 does not allow the project folder and the Gradle data cache folder to be on different drives.
Move the project to the same drive as your Gradle cache/home directory, or update layout.buildDirectory.
Or you can set Gradle user home directory (defined by the “GRADLE_USER_HOME” environment variable, which defaults to USER_HOME/.gradle)
If you customized buildDir in build.gradle.kts, ensure it is on the same drive as the root project.
Run ./gradlew clean and invalidate IDE caches.

**Comment by axoking** [comment]
@SysoenkovDmitry 

> KSP 2.0 does not allow the project folder and the Gradle data cache folder to be on different drives.

I noticed that, but the question is WHY. I don't  see any reason why it should be like that, and it causes problems for a lot of people.

**Comment by axoking** [comment]
Does anyone know **where** that bug originates from?

Like, what function throws the `IllegalArgumentException`? Where is it called? What is it trying to do?

**Comment by SysoenkovDmitry** [comment]
Internal mechanism uses relative paths to ensure build consistency and correct caching behavior across different environments.
I don’t know why they implemented it this way, but we have to live with it.

**Comment by axoking** [comment]
@SysoenkovDmitry couldn‘t we add absolute paths as a fallback when relative path calculation fails? I mean that‘s still better than erroring

**Comment by jaschdoc** [comment]
Hi, this is certainly a bug. I understand it can be annoying, but I can't promise when it will be fixed. However, we are aware of it.

**Comment by xiaoxing1992** [comment]
> 嗨，这确实是个 bug。我理解这可能很烦人，但我不能保证何时会修复。不过，我们已经意识到了这个问题。

hello ，May I ask when you will be able to fix this issue—which is kind of a half-issue? If it causes problems when on different drive letters, it will lead to more people being confused.

**Comment by NinaThornhill** [comment]
I'd also like to ask when there will be some progress on this issue for users who have more than one drive. Many work hours are being consumed ....
