### ISSUE TITLE
Error retrieving Kotlin modifiers

### ISSUE THREAD

**Issue by graemerocher** [google/ksp#1276]
Seeing this error for some types when retrieving Kotlin modifiers for properties:

```
e: [ksp] java.lang.IllegalStateException: unhandled visibility: invisible_fake
        at com.google.devtools.ksp.DescriptorUtilsKt.toKSModifiers(DescriptorUtils.kt:94)
        at com.google.devtools.ksp.symbol.impl.binary.KSPropertyAccessorDescriptorImpl$modifiers$2.invoke(KSPropertyAccessorDescriptorImpl.kt:58)
        at com.google.devtools.ksp.symbol.impl.binary.KSPropertyAccessorDescriptorImpl$modifiers$2.invoke(KSPropertyAccessorDescriptorImpl.kt:56)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
```

**Comment by ting-yuan** [comment]
Hello @graemerocher, would you mind sharing more info about the property? The exception is thrown for unexpected cases.

**Comment by graemerocher** [comment]
so the type where this problem originates from is in the JSR-330 TCK classes we use. Basically the `roundThingPackagePrivateMethod2Injected` method of this class:

```kotlin
import jakarta.inject.Inject

open class RoundThing {

    var roundThingPackagePrivateMethod2Injected: Boolean = false
        private set

    var roundThingPackagePrivateMethod3Injected: Boolean = false
        private set

    var roundThingPackagePrivateMethod4Injected: Boolean = false
        private set

    @Inject open internal fun injectPackagePrivateMethod2() {
        roundThingPackagePrivateMethod2Injected = true
    }

    @Inject open internal fun injectPackagePrivateMethod3() {
        roundThingPackagePrivateMethod3Injected = true
    }

    @Inject open internal fun injectPackagePrivateMethod4() {
        roundThingPackagePrivateMethod4Injected = true
    }
}
```

There are another two subclasses of this type that may be involved as well. The classes that produce this error can be found here:

https://github.com/micronaut-projects/micronaut-core/tree/4.0.x/test-suite-kotlin-ksp/src/test/kotlin/org/atinject/jakartatck/auto/accessories
