### ISSUE TITLE
Run command line crashed with OutOfMemoryError

### ISSUE THREAD

**Issue by rome753** [google/ksp#1303]
I run ksp command line according to the doc: https://kotlinlang.org/docs/ksp-command-line.html
If there are several kotlin files in my project directory, it works well.
But if there are hundreds of kotlin files, it crashed with java.lang.OutOfMemoryError.

```java
exception: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.ArrayList.<init>(ArrayList.java:153)
	at org.jetbrains.kotlin.protobuf.SmallSortedMap.ensureEntryArrayMutable(SmallSortedMap.java:391)
	at org.jetbrains.kotlin.protobuf.SmallSortedMap.put(SmallSortedMap.java:243)
	at org.jetbrains.kotlin.protobuf.FieldSet.setField(FieldSet.java:259)
	at org.jetbrains.kotlin.protobuf.GeneratedMessageLite.parseUnknownField(GeneratedMessageLite.java:618)
	at org.jetbrains.kotlin.protobuf.GeneratedMessageLite.access$100(GeneratedMessageLite.java:49)
	at org.jetbrains.kotlin.protobuf.GeneratedMessageLite$ExtendableMessage.parseUnknownField(GeneratedMessageLite.java:246)
	at org.jetbrains.kotlin.metadata.ProtoBuf$Function.<init>(ProtoBuf.java:15629)
	at org.jetbrains.kotlin.metadata.ProtoBuf$Function.<init>(ProtoBuf.java:15587)
	at org.jetbrains.kotlin.metadata.ProtoBuf$Function$1.parsePartialFrom(ProtoBuf.java:15817)
	at org.jetbrains.kotlin.metadata.ProtoBuf$Function$1.parsePartialFrom(ProtoBuf.java:15812)
	at org.jetbrains.kotlin.protobuf.CodedInputStream.readMessage(CodedInputStream.java:495)
	at org.jetbrains.kotlin.metadata.ProtoBuf$Package.<init>(ProtoBuf.java:12848)
	at org.jetbrains.kotlin.metadata.ProtoBuf$Package.<init>(ProtoBuf.java:12795)
	at org.jetbrains.kotlin.metadata.ProtoBuf$Package$1.parsePartialFrom(ProtoBuf.java:12926)
	at org.jetbrains.kotlin.metadata.ProtoBuf$Package$1.parsePartialFrom(ProtoBuf.java:12921)
	at org.jetbrains.kotlin.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:192)
	at org.jetbrains.kotlin.protobuf.AbstractParser.parseFrom(AbstractParser.java:209)
	at org.jetbrains.kotlin.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
	at org.jetbrains.kotlin.metadata.ProtoBuf$Package.parseFrom(ProtoBuf.java:13209)
	at org.jetbrains.kotlin.metadata.jvm.deserialization.JvmProtoBufUtil.readPackageDataFrom(JvmProtoBufUtil.kt:42)
	at org.jetbrains.kotlin.metadata.jvm.deserialization.JvmProtoBufUtil.readPackageDataFrom(JvmProtoBufUtil.kt:37)
	at org.jetbrains.kotlin.load.kotlin.DeserializedDescriptorResolver.createKotlinPackagePartScope(DeserializedDescriptorResolver.kt:66)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.JvmPackageScope$kotlinScopes$2.invoke(JvmPackageScope.kt:47)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.JvmPackageScope$kotlinScopes$2.invoke(JvmPackageScope.kt:44)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:408)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(LockBasedStorageManager.java:527)
	at org.jetbrains.kotlin.storage.StorageKt.getValue(storage.kt:42)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.JvmPackageScope.getKotlinScopes(JvmPackageScope.kt:44)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.JvmPackageScope.getContributedClassifier(JvmPackageScope.kt:58)
	at org.jetbrains.kotlin.resolve.scopes.ChainedMemberScope.getContributedClassifier(ChainedMemberScope.kt:35)
	at org.jetbrains.kotlin.resolve.scopes.AbstractScopeAdapter.getContributedClassifier(AbstractScopeAdapter.kt:44)
```

I run with command line, so not need gradle or Android Studio.

I add jvm options to increase the head size, but no work.
```java
-Dkotlin.daemon.jvm.options="-Xms2g -Xmx12g
```

Here is my command write in Python.
```python
('kotlinc -Dkotlin.daemon.jvm.options="-Xms2g -Xmx12g -XX:+UseG1GC -XX:G1HeapRegionSize=2048m -XX:MaxGCPauseMillis=5000 -XX:MaxPermSize=700m -XX:ReservedCodeCacheSize=480m" '
    '-Xplugin=' + KSP_PLUGIN_JAR + ' '
    '-Xplugin=' + KSP_API_JAR + ' '
    '-Xallow-no-source-files '
    '-P plugin:com.google.devtools.ksp.symbol-processing:apclasspath=' + AP + ' '
    '-P plugin:com.google.devtools.ksp.symbol-processing:projectBaseDir=' + projPath + ' '
    '-P plugin:com.google.devtools.ksp.symbol-processing:incremental=false '
    '-P plugin:com.google.devtools.ksp.symbol-processing:classOutputDir=../generate '
    '-P plugin:com.google.devtools.ksp.symbol-processing:javaOutputDir=../generate '
    '-P plugin:com.google.devtools.ksp.symbol-processing:kotlinOutputDir=../generate '
    '-P plugin:com.google.devtools.ksp.symbol-processing:resourceOutputDir=../generate '
    '-P plugin:com.google.devtools.ksp.symbol-processing:kspOutputDir=../generate '
    '-P plugin:com.google.devtools.ksp.symbol-processing:cachesDir=../generate '
    '' + projPath)
```

**Comment by ting-yuan** [comment]
Would you mind sharing some more stack trace where `com.google.devtools.ksp` appears? So that we can have a better clue. Specifically, is there any deep recursion?

On the other hand, would compiling those files (without calling KSP first, if possible) trigger the same OOM error?

**Comment by rome753** [comment]
I tried compiling without calling KSP, also got OOM.

**Comment by neetopia** [comment]
That sounds like a general Java memory issue with your JVM configuration. E.g. if you are on Windows, setting max heap size might require additional effort.
