### ISSUE TITLE
KSP conflict with KGP, which causes failures with Android Studio

### ISSUE THREAD

**Issue by skorudzhiev** [google/ksp#1347]
Incompatibility between KSP and KGP after attempting several different version combinations of the aforementioned plugins.
More information can be referenced in the following issue [https://issuetracker.google.com/issues/270166324](https://issuetracker.google.com/issues/270166324)

```
Caused by: java.lang.NoClassDefFoundError: org/jetbrains/kotlin/gradle/plugin/mpp/pm20/KotlinCompilationData
	at com.google.devtools.ksp.gradle.KspGradleSubplugin.applyToCompilation(KspSubplugin.kt:416)
	at org.jetbrains.kotlin.gradle.plugin.SubpluginEnvironment.addSubpluginOptions(SubpluginEnvironment.kt:49)
	at org.jetbrains.kotlin.gradle.plugin.AndroidProjectHandler$configureTarget$2$1.invoke(AndroidProjectHandler.kt:106)
	at org.jetbrains.kotlin.gradle.plugin.AndroidProjectHandler$configureTarget$2$1.invoke(AndroidProjectHandler.kt:101)
	at org.jetbrains.kotlin.gradle.utils.ForEachAndroidVariantKt$sam$org_gradle_api_Action$0.execute(forEachAndroidVariant.kt)
```

**Comment by neetopia** [comment]
The error says it is not able to find `KotlinCompilationData`, which should be presented in KGP 1.8.10, can you check the KGP version used by AGP 7.4.1?

**Comment by skorudzhiev** [comment]
I can confirm that the version of KGP that is currently being used is `1.8.10`

**Comment by neetopia** [comment]
Oops, my mistake, I meant checking Gradle version used by AGP.

**Comment by skorudzhiev** [comment]
The version of Gradle that we use is `7.6`

**Comment by neetopia** [comment]
tried 7.6 Gradle with AGP 7.4.1 in KSP's gradle plugin tests, seems to be working after setting target compatibility to Java 11( won't compile with 8 anyways after upgrading Gradle), can you provide a reproduce link for this?

**Comment by skorudzhiev** [comment]
I can provide logs if they can help. Please be more specific in your request. This is an issue related to the environment which affects post-built project configuration.  Please have a look at the original thread created in the [issue tracker](https://issuetracker.google.com/issues/270166324) and let me know what other type of information might be useful for investigating the problem.

**Comment by mtotschnig** [comment]
In my case I got this error, in a project where I was using kotlin '1.8.21' with ksp '1.8.10-1.0.9'. Android Studio just showed above error message, but running gradle from the command line, I got the following message:

`ksp-1.8.10-1.0.9 is too old for kotlin-1.8.21. Please upgrade ksp or downgrade kotlin-gradle-plugin to 1.8.10.`

Upgrading ksp to "1.8.21-1.0.11" solved the problem.

**Comment by Fly-Felix** [comment]
> In my case I got this error, in a project where I was using kotlin '1.8.21' with ksp '1.8.10-1.0.9'. Android Studio just showed above error message, but running gradle from the command line, I got the following message:
> 
> `ksp-1.8.10-1.0.9 is too old for kotlin-1.8.21. Please upgrade ksp or downgrade kotlin-gradle-plugin to 1.8.10.`
> 
> Upgrading ksp to "1.8.21-1.0.11" solved the problem.

It worked, thank you very much

**Comment by gustavobarbosab** [comment]
> In my case I got this error, in a project where I was using kotlin '1.8.21' with ksp '1.8.10-1.0.9'. Android Studio just showed above error message, but running gradle from the command line, I got the following message:
> 
> `ksp-1.8.10-1.0.9 is too old for kotlin-1.8.21. Please upgrade ksp or downgrade kotlin-gradle-plugin to 1.8.10.`
> 
> Upgrading ksp to "1.8.21-1.0.11" solved the problem.

Thanks, @mtotschnig, it works for me.

**Comment by MoatazBadawy** [comment]
> In my case I got this error, in a project where I was using kotlin '1.8.21' with ksp '1.8.10-1.0.9'. Android Studio just showed above error message, but running gradle from the command line, I got the following message:
> 
> `ksp-1.8.10-1.0.9 is too old for kotlin-1.8.21. Please upgrade ksp or downgrade kotlin-gradle-plugin to 1.8.10.`
> 
> Upgrading ksp to "1.8.21-1.0.11" solved the problem.

Thanks for your solution. You may need to update the Google developers documentation with the new version as the old one failed with most of us. Thanks!

**Comment by oscar066** [comment]
> In my case I got this error, in a project where I was using kotlin '1.8.21' with ksp '1.8.10-1.0.9'. Android Studio just showed above error message, but running gradle from the command line, I got the following message:
> 
> `ksp-1.8.10-1.0.9 is too old for kotlin-1.8.21. Please upgrade ksp or downgrade kotlin-gradle-plugin to 1.8.10.`
> 
> Upgrading ksp to "1.8.21-1.0.11" solved the problem.

Thank you for the solution. In my case, the KSP plugin version 1.8.21-1.0.11 was too old and incompatible with Kotlin version 1.9.0. I resolved the error by updating to KSP version 1.9.0-1.0.13, which is compatible with Kotlin 1.9.0.

**Comment by Gianguyen1234** [comment]
I added ksp successfully by using this way: https://youtu.be/skEThDQWLig?si=gtzPnFR-FYgzyQvl

**Comment by Vcky4** [comment]
> In my case I got this error, in a project where I was using kotlin '1.8.21' with ksp '1.8.10-1.0.9'. Android Studio just showed above error message, but running gradle from the command line, I got the following message:
> 
> `ksp-1.8.10-1.0.9 is too old for kotlin-1.8.21. Please upgrade ksp or downgrade kotlin-gradle-plugin to 1.8.10.`
> 
> Upgrading ksp to "1.8.21-1.0.11" solved the problem.

Thanks, this worked for me

**Comment by hii-deepak** [comment]
> In my case I got this error, in a project where I was using kotlin '1.8.21' with ksp '1.8.10-1.0.9'. Android Studio just showed above error message, but running gradle from the command line, I got the following message:
> 
> `ksp-1.8.10-1.0.9 is too old for kotlin-1.8.21. Please upgrade ksp or downgrade kotlin-gradle-plugin to 1.8.10.`
> 
> Upgrading ksp to "1.8.21-1.0.11" solved the problem.

It worked, thank you very much

**Comment by chunkingz** [comment]
> > In my case I got this error, in a project where I was using kotlin '1.8.21' with ksp '1.8.10-1.0.9'. Android Studio just showed above error message, but running gradle from the command line, I got the following message:
> > `ksp-1.8.10-1.0.9 is too old for kotlin-1.8.21. Please upgrade ksp or downgrade kotlin-gradle-plugin to 1.8.10.`
> > Upgrading ksp to "1.8.21-1.0.11" solved the problem.
> 
> Thank you for the solution. In my case, the KSP plugin version 1.8.21-1.0.11 was too old and incompatible with Kotlin version 1.9.0. I resolved the error by updating to KSP version 1.9.0-1.0.13, which is compatible with Kotlin 1.9.0.

in 2024 this one has worked for me. I guess my question now would be how do we know what version to update to as the docs [here](https://kotlinlang.org/docs/ksp-quickstart.html#use-your-own-processor-in-a-project) don't show it as expected.
