### ISSUE TITLE
Unable to load class 'org.jetbrains.kotlin.config.LanguageVersion

### ISSUE THREAD

**Issue by guozhiqiang123** [google/ksp#1358]
```
exception: java.lang.NoSuchMethodError: 'kotlin.KotlinVersion org.jetbrains.kotlin.config.LanguageVersionSettingsKt.toKotlinVersion(org.jetbrains.kotlin.config.LanguageVersion)'
	at com.google.devtools.ksp.KspOptions$Builder.<init>(KspOptions.kt:90)
	at com.google.devtools.ksp.KotlinSymbolProcessingCommandLineProcessor.processOption(KotlinSymbolProcessingPlugin.kt:54)
	at org.jetbrains.kotlin.cli.jvm.plugins.PluginCliParserKt.processCompilerPluginsOptions(PluginCliParser.kt:125)
	at org.jetbrains.kotlin.cli.jvm.plugins.PluginCliParser.processPluginOptions(PluginCliParser.kt:83)
	at org.jetbrains.kotlin.cli.jvm.plugins.PluginCliParser.loadPlugins(PluginCliParser.kt:72)
	at org.jetbrains.kotlin.cli.jvm.plugins.PluginCliParser.loadPluginsSafe(PluginCliParser.kt:44)
	at org.jetbrains.kotlin.cli.common.CLICompiler.loadPlugins(CLICompiler.kt:179)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:69)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:52)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:88)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:44)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:98)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:76)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:45)
	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit(CLITool.kt:227)
	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit$default(CLITool.kt:222)
	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMain(CLITool.kt:214)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler$Companion.main(K2JVMCompiler.kt:271)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.main(K2JVMCompiler.kt)

```

kotlin_version=1.8.0
compileSdk=33

**Comment by neetopia** [comment]
what's the KSP version you are using? Note that if there is a mismatch between the KSP version and the compiler version, such errors can occur.

**Comment by guozhiqiang123** [comment]
ksp_plugin=1.8.10-1.0.9

**Comment by neetopia** [comment]
I would suggest to upgrade compiler version to 1.8.10 to match KSP, or use a lower KSP version to match compiler.

**Comment by guozhiqiang123** [comment]
Thanks!
It works when I do these:①upgrade kotlin 1.7.10 to 1.8.10 ;   ②upgrade gradle 6.8.3 to 7.5.1 ;   ③upgrade AGP  4.2.0 to 7.3.1
