### ISSUE TITLE
KSTypeReference.resolve  NullPointerException

### ISSUE THREAD

**Issue by LiushuiXiaoxia** [google/ksp#1390]
`KSTypeReference.resolve() ` cause  `NullPointerException`

I want to get`KSType` of function's parameters 

```
public class TestJava extends TestJava1<Object> {

    public void setO(Provider<? extends TestJava> o) {
        this.o = o;
    }

    @Autowired("ss")
    public Provider<? extends TestJava> o = null;

    public void tt() {
        //LoginService s = null;
    }


    class Inner extends TestJava1<String> {

        @Autowired("omg")
        private Provider<? extends TestJava1> o2;

        public void setO2(Provider<? extends TestJava1> o2) {
            this.o2 = o2;
        }
    }
}
```

such as I want get `TestJava.Inner#setO2() ` function , the function's  `o2` parameters occurs error.

```
fun KSValueParameter.parseServiceDependency(serviceName: String? = null) {
    LogKit.warn("parseServiceDependency.type = ${type}, element = ${type.element}")
    val t = type.resolve() // NullPointerException
}
```

The following is the log

```
e: [ksp] java.lang.NullPointerException
	at com.google.devtools.ksp.processing.impl.ResolverImpl.resolveJavaType(ResolverImpl.kt:635)
	at com.google.devtools.ksp.processing.impl.ResolverImpl.resolveUserType(ResolverImpl.kt:724)
	at com.google.devtools.ksp.symbol.impl.java.KSTypeReferenceJavaImpl.resolve(KSTypeReferenceJavaImpl.kt:118)
	at com.xx.lib.blrouter.ksp.internal.Ksp_extKt.parseServiceDependency(ksp-ext.kt:343)
	at com.xx.lib.blrouter.ksp.internal.Ksp_extKt.parseAutoWired(ksp-ext.kt:444)
```

But when I write like this, It's ok.

```
public class TestJava extends TestJava1<Object> {

    public void setO(Provider<? extends TestJava> o) {
        this.o = o;
    }

    @Autowired("ss")
    public Provider<? extends TestJava> o = null;

    public void tt() {
        //LoginService s = null;
    }


//    class Inner extends TestJava1<String> {
//
//        @Autowired("omg")
//        private Provider<? extends TestJava1> o2;
//
//        public void setO2(Provider<? extends TestJava1> o2) {
//            this.o2 = o2;
//        }
//    }
}

class Inner extends TestJava1<String> {

    @Autowired("omg")
    private Provider<? extends TestJava1> o2;

    public void setO2(Provider<? extends TestJava1> o2) {
        this.o2 = o2;
    }
}
```

**Comment by LiushuiXiaoxia** [comment]
ksp version

```
api("com.google.devtools.ksp:symbol-processing-api:1.7.10-1.0.6")
```

**Comment by neetopia** [comment]
Can you try upgrade to the latest KSP version to see if problem resolves? Note that you also need to upgrade compiler version.

**Comment by LiushuiXiaoxia** [comment]
```
api("com.google.devtools.ksp:symbol-processing-api:1.7.20-1.0.8")
```
It's ok,  😄
