### ISSUE TITLE
Generated classes cannot be used in annotations

### ISSUE THREAD

**Issue by dzikoysk** [google/ksp#1391]
I'm generating an object with const values that looks like this:

```kotlin
object UserTableNames {
  public const val ID = "id"
}
```

This object is generated from a code like that:

```kotlin
@Definition(/* annnoation content, whatever */)
object UserDefinition
```

Later on, I'd like to use these generated consts in another annotation that I'll be processing:

```kotlin
@DtoDefinition(
    from = UserDefinition::class,
    variants = [
        Variant(name = "UserDto", properties = [ UserTableNames.ID ]),
    ]
)
object UserDtoDefinition
```

I was kinda surprised, when the value of `@Variant` where `[ name ="UserDto", properties = [] ]`. I've played a little bit with it, and I've found out that these generated classes are simply not supported in processed annotations, because when I use any other generated content in non-array property (e.g. `from = UserTableNames::class`), then it simply throws:

```
[ksp] java.util.NoSuchElementException: Collection contains no element matching the predicate.
	at com.google.devtools.ksp.UtilsKt.createInvocationHandler$lambda$8(utils.kt:553)
	at jdk.proxy16/jdk.proxy16.$Proxy124.from(Unknown Source)
```

At first, I was doing it all in the one round, but then I've moved `@DtoDefinition` processing to the next phase - unfortunately, the result is the same. Summing up, there are two issues:

1. I cannot find a way to use generated classes in annotation in the same module using the same processor - as long as I understand it might be a problem for the single round, I'd expect the second one to catch up the generated content
2. Arrays silently fail by dropping unknown entries from the list - it should probably just throw immediately

**Comment by neetopia** [comment]
It seems to be a multiple round issue. You are right about it should not work in single round anyways. Can you provide a reproduce repo for this issue? Thanks.

**Comment by dzikoysk** [comment]
I didn't touch [the affected branch](https://github.com/dzikoysk/sqiffy/pull/40) since I've reported it, so I've just updated it from [1.8.22-1.0.11](https://github.com/google/ksp/releases/tag/1.8.22-1.0.11) -> [1.9.0-1.0.11](https://github.com/google/ksp/releases/tag/1.9.0-1.0.11) and it solved the issue for me. I mean, I cannot reproduce the `#1` now, so I can only assume that `#2` still can be somehow triggered if array contains non-existing symbol at compile-time.
