### ISSUE TITLE
Fails to resolve type annotation on suspend function

### ISSUE THREAD

**Issue by wanyingd1996** [google/ksp#1416]
Hi, all, I ran into a tricky bug from ksp.

When I have an interface like:
```
interface MainInterface {
  suspend fun invoke(): Set<@JvmSuppressWildcards String>
}
```
And referencing the type from another type's constructor:
```
public class MainBinding {
  @Inject MainBinding(MainInterface funcClass) {}
}
```
I ran into errors coming from ksp/kotlinc when it tries to resolve constructor parameters in MainBinding
```
Caused by: java.lang.IllegalArgumentException: Failed requirement.
	at org.jetbrains.kotlin.load.java.structure.impl.classFiles.BinaryJavaAnnotation$Companion.computeTargetType$resolution_common_jvm(Annotations.kt:179)
	at org.jetbrains.kotlin.load.java.structure.impl.classFiles.AnnotationsAndParameterCollectorMethodVisitor.visitTypeAnnotation$getTargetType(Annotations.kt:110)
	at org.jetbrains.kotlin.load.java.structure.impl.classFiles.AnnotationsAndParameterCollectorMethodVisitor.visitTypeAnnotation(Annotations.kt:118)
	at org.jetbrains.org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1420)
	at org.jetbrains.org.objectweb.asm.ClassReader.accept(ClassReader.java:712)
	at org.jetbrains.org.objectweb.asm.ClassReader.accept(ClassReader.java:395)
	at org.jetbrains.kotlin.load.java.structure.impl.classFiles.BinaryJavaClass.<init>(BinaryJavaClass.kt:117)
at org.jetbrains.kotlin.load.java.structure.impl.classFiles.BinaryJavaClass.<init>(BinaryJavaClass.kt:122)
	at org.jetbrains.kotlin.load.java.structure.impl.classFiles.BinaryJavaClass.<init>(BinaryJavaClass.kt:34)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCliJavaFileManagerImpl.findClass(KotlinCliJavaFileManagerImpl.kt:132)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCliJavaFileManagerImpl.findClass(KotlinCliJavaFileManagerImpl.kt:102)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCliJavaFileManagerImpl$findClass$$inlined$getOrPut$lambda$1.invoke(KotlinCliJavaFileManagerImpl.kt:130)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCliJavaFileManagerImpl$findClass$$inlined$getOrPut$lambda$1.invoke(KotlinCliJavaFileManagerImpl.kt:48)
	at org.jetbrains.kotlin.load.java.structure.impl.classFiles.ClassifierResolutionContext.resolveClass(ClassifierResolutionContext.kt:58)
	at org.jetbrains.kotlin.load.java.structure.impl.classFiles.ClassifierResolutionContext.resolveByInternalName$resolution_common_jvm(ClassifierResolutionContext.kt:99)
	at org.jetbrains.kotlin.load.java.structure.impl.classFiles.BinaryClassSignatureParser$parseParameterizedClassRefSignature$1.invoke(BinaryClassSignatureParser.kt:145)
	at org.jetbrains.kotlin.load.java.structure.impl.classFiles.BinaryClassSignatureParser$parseParameterizedClassRefSignature$1.invoke(BinaryClassSignatureParser.kt:145)
	at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
	at org.jetbrains.kotlin.load.java.structure.impl.classFiles.PlainJavaClassifierType.getClassifierResolverResult(Types.kt:39)
	at org.jetbrains.kotlin.load.java.structure.impl.classFiles.PlainJavaClassifierType.isRaw(Types.kt:44)
	at org.jetbrains.kotlin.load.java.lazy.types.JavaTypeResolver.transformJavaClassifierType(JavaTypeResolver.kt:102)
	at org.jetbrains.kotlin.load.java.lazy.types.JavaTypeResolver.transformJavaType(JavaTypeResolver.kt:58)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaScope.resolveValueParameters(LazyJavaScope.kt:223)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaClassMemberScope.resolveConstructor(LazyJavaClassMemberScope.kt:695)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaClassMemberScope.access$resolveConstructor(LazyJavaClassMemberScope.kt:63)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaClassMemberScope$constructors$1.invoke(LazyJavaClassMemberScope.kt:87)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaClassMemberScope$constructors$1.invoke(LazyJavaClassMemberScope.kt:83)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:408)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(LockBasedStorageManager.java:527)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaClassDescriptor.getConstructors(LazyJavaClassDescriptor.kt:146)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaClassDescriptor.getConstructors(LazyJavaClassDescriptor.kt:42)
	at com.google.devtools.ksp.symbol.impl.binary.KSClassDeclarationDescriptorImpl$declarations$2.invoke(KSClassDeclarationDescriptorImpl.kt:111)
	at com.google.devtools.ksp.symbol.impl.binary.KSClassDeclarationDescriptorImpl$declarations$2.invoke(KSClassDeclarationDescriptorImpl.kt:100)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.google.devtools.ksp.symbol.impl.binary.KSClassDeclarationDescriptorImpl.getDeclarations(KSClassDeclarationDescriptorImpl.kt:100)
	at com.google.devtools.ksp.UtilsKt.getDeclaredFunctions(utils.kt:94)
	at com.google.devtools.ksp.UtilsKt.getConstructors(utils.kt:108)
```

Note to repro this failure, it requires a special setup.

The interface itself is included in one of the buildable unit A, another buildable unit B depends on A to have access to B interface, and when ksp is running for unit B, we fails to resolve the type annotation. If we combine sources from A and B to be a single buildable unit, then we won't have this issue. So I feel like the problem is the information generated by A wasn't passed to B correctly. I think this is a bug from ksp, because I'm not seeing the same issue from kapt.

**Comment by neetopia** [comment]
I tried to reproduce this issue in your setup but can't seem to reproduce it, here is my [branch](https://github.com/neetopia/ksp/tree/type-annotation) containing the test, let me know if I misunderstood your setup.

**Comment by ting-yuan** [comment]
This is a bug in the compiler backend, which generated incorrect target type path of the type annotation in the class file. Here is the upstream bug: https://youtrack.jetbrains.com/issue/KT-60509

Unfortunately, there's nothing that can be done by KSP. A few workarounds might be possible by users depending on the context:
1. Don't pass `-Xemit-jvm-type-annotations` to kotlinc when building libraries that can be read by KSP.
2. Place `@JvmSuppressWildcard` on the function, property or class; Do not use type annotation in nested type parameters that wildcards are involved.

**Comment by ting-yuan** [comment]
@wanyingd1996 Sorry to bring this old thread to your attention. Because this is an issue that the Kotlin compiler generated wrong code in the library, the only thing we could do is perhaps intercepting exception due to parse error, and return a null or empty list. If I understand correctly, Java annotation processors also suffer from the same issue and the best they can do is the same. Do you happen to know what the behavior of Java annotation processors are?

**Comment by wanyingd1996** [comment]
My repro is under //experimental/users/wanyingd/java/dagger/ksp3: dagger, which only fails when I build with dagger ksp processors.
