### ISSUE TITLE
KSP processing fails with Java enum

### ISSUE THREAD

**Issue by dstepanov** [google/ksp#1482]
Originally reported here https://github.com/micronaut-projects/micronaut-core/issues/9642

I found a few different exceptions:
```
e: [ksp] java.lang.IllegalStateException: unexpected class: class com.google.devtools.ksp.symbol.impl.java.KSClassDeclarationJavaEnumEntryImpl
        at com.google.devtools.ksp.processing.impl.ResolverImpl.resolveClassDeclaration(ResolverImpl.kt:568)
        at com.google.devtools.ksp.processing.impl.ResolverImpl.mapToJvmSignatureInternal$compiler_plugin(ResolverImpl.kt:356)
        at com.google.devtools.ksp.processing.impl.ResolverImpl.mapToJvmSignature(ResolverImpl.kt:353)
        at io.micronaut.kotlin.processing.ExtensionsKt.getBinaryName(extensions.kt:47)
        at io.micronaut.kotlin.processing.visitor.KotlinClassElement$KotlinEnclosedElementsQuery.getElementName(KotlinClassElement.kt:628)
        at io.micronaut.kotlin.processing.visitor.KotlinClassElement$KotlinEnclosedElementsQuery.getElementName(KotlinClassElement.kt:619)
        at io.micronaut.inject.ast.utils.EnclosedElementsQuery.getAllElements(EnclosedElementsQuery.java:217)
```

```
e: [ksp] /Users/denisstepanov/dev/micronaut-core/test-suite-kotlin-ksp/src/test/kotlin/io/micronaut/core/beans/JavaEnum.java:3: Member must have a containing class: PsiMethod:valueOf
e: java.lang.AssertionError: Member must have a containing class: PsiMethod:valueOf
        at org.jetbrains.kotlin.load.java.structure.impl.JavaMemberImpl.getContainingClass(JavaMemberImpl.java:63)
        at com.google.devtools.ksp.symbol.impl.UtilsKt.resolveContainingClass(utils.kt:235)
        at com.google.devtools.ksp.processing.impl.ResolverImpl.resolveJavaDeclaration(ResolverImpl.kt:537)
        at com.google.devtools.ksp.processing.impl.ResolverImpl.resolveFunctionDeclaration(ResolverImpl.kt:577)
        at com.google.devtools.ksp.symbol.impl.java.KSFunctionDeclarationJavaImpl.findOverridee(KSFunctionDeclarationJavaImpl.kt:56)
        at io.micronaut.kotlin.processing.annotation.KotlinAnnotationMetadataBuilder.methodsHierarchy(KotlinAnnotationMetadataBuilder.kt:273)

```

"1.8.21-1.0.11"

**Comment by runenielsen** [comment]
Any news on this? I get this exact error following this example, but with a Kotlin application instead of Java: https://guides.micronaut.io/latest/micronaut-openapi-generator-server-gradle-java.html

Shame if the Micronaut OpenAPI server generator doesn't work with Kotlin.

**Comment by dstepanov** [comment]
@runenielsen The solution should be to put the Java classes into the Java folder

**Comment by runenielsen** [comment]
@dstepanov: The generated Java models are already in the path:

build/generated/openapi/generateServerOpenApiModels/src/main/java

... and this path is part of the Java source set of the application.

So they are already in a Java folder...

**Comment by dstepanov** [comment]
I thought for the people in the issue that is a workaround

**Comment by opaquot** [comment]
Hi. I'm having the same issue. Are there any news on this?

**Comment by pshemass** [comment]
any update on this?

**Comment by sgammon** [comment]
makes ksp unusable with protobuf
