### ISSUE TITLE
Use of Array<String> in the annotation class is not supported in the kotlin native

### ISSUE THREAD

**Issue by qdsfdhvh** [google/ksp#1487]
I use the following annotations:

```kotlin
@Retention(AnnotationRetention.SOURCE)
@Target(AnnotationTarget.FUNCTION)
annotation class NavGraphDestination(
    val route: String,
    val deepLinks: Array<String> = emptyArray(),
    val packageName: String = "",
    val functionName: String = "scene",
)
```

When I call `destination.deepLinks`, I get the following error:
```
 exception: info: [ksp] loaded provider(s): [io.github.seiko.precompose.RouteGraphProcessorProvider]
exception: error: [ksp] java.lang.IllegalStateException: unhandled value type, please file a bug at https://github.com/google/ksp/issues/new
exception:      at com.google.devtools.ksp.UtilsKt.createInvocationHandler$lambda$8(utils.kt:381)
exception:      at jdk.proxy3/jdk.proxy3.$Proxy23.deepLinks(Unknown Source)
exception:      at io.github.seiko.precompose.symbol.NavGraphDestinationDeclarationKt.of(NavGraphDestinationDeclaration.kt:33)
exception:      at io.github.seiko.precompose.destination.NavGraphDestinationGenerator$collectNavGraphDestination$1.invoke(NavGraphDestinationGenerator.kt:29)
exception:      at io.github.seiko.precompose.destination.NavGraphDestinationGenerator$collectNavGraphDestination$1.invoke(NavGraphDestinationGenerator.kt:29)
exception:      at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
exception:      at io.github.seiko.precompose.destination.NavGraphDestinationGenerator.generate(NavGraphDestinationGenerator.kt:33)
exception:      at io.github.seiko.precompose.RouteGraphProcessor.process(RouteGraphProcessor.kt:25)
exception:      at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$6$1.invoke(KotlinSymbolProcessingExtension.kt:291)
exception:      at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$6$1.invoke(KotlinSymbolProcessingExtension.kt:289)
exception:      at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.handleException(KotlinSymbolProcessingExtension.kt:394)
exception:      at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.doAnalysis(KotlinSymbolProcessingExtension.kt:289)
exception:      at org.jetbrains.kotlin.analyzer.common.CommonResolverForModuleFactory$Companion.analyzeFiles(CommonResolverForModuleFactory.kt:193)
exception:      at org.jetbrains.kotlin.analyzer.common.CommonResolverForModuleFactory$Companion.analyzeFiles$default(CommonResolverForModuleFactory.kt:133)
exception:      at org.jetbrains.kotlin.cli.metadata.CommonAnalysisKt$runCommonAnalysisIteration$1.invoke(CommonAnalysis.kt:70)
exception:      at org.jetbrains.kotlin.cli.metadata.CommonAnalysisKt$runCommonAnalysisIteration$1.invoke(CommonAnalysis.kt)
exception:      at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:115)
exception:      at org.jetbrains.kotlin.cli.metadata.CommonAnalysisKt.runCommonAnalysisIteration(CommonAnalysis.kt:69)
exception:      at org.jetbrains.kotlin.cli.metadata.CommonAnalysisKt.runCommonAnalysisForSerialization(CommonAnalysis.kt:42)
exception:      at org.jetbrains.kotlin.cli.metadata.K2MetadataKlibSerializer.serialize(K2MetadataKlibSerializer.kt:48)
exception:      at org.jetbrains.kotlin.cli.metadata.K2MetadataCompiler.doExecute(K2MetadataCompiler.kt:122)
exception:      at org.jetbrains.kotlin.cli.metadata.K2MetadataCompiler.doExecute(K2MetadataCompiler.kt:40)
exception:      at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:100)
exception:      at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:46)
exception:      at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
exception:      at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:79)
exception:      at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:43)
exception:      at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit(CLITool.kt:180)
exception:      at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit$default(CLITool.kt:178)
exception:      at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMain(CLITool.kt:167)
exception:      at org.jetbrains.kotlin.cli.metadata.K2MetadataCompiler$Companion.main(K2MetadataCompiler.kt:142)
exception:      at org.jetbrains.kotlin.cli.metadata.K2MetadataCompiler.main(K2MetadataCompiler.kt)
exception: 
exception: error: error occurred in KSP, check log for detail
```

**Comment by mikedawson** [comment]
This looks like the same bug that I saw on compiling to Kotlin/JS . It didn't cause a problem on JVM and Android. I found I could workaround it using KSAnnotation manually : see issue #1503

**Comment by qdsfdhvh** [comment]
> This looks like the same bug that I saw on compiling to Kotlin/JS . It didn't cause a problem on JVM and Android. I found I could workaround it using KSAnnotation manually : see issue #1503

Thanks, I tried it and it works.

**Comment by mikedawson** [comment]
Hi - happy to hear that workaround worked for you. That said, I still think this is an unresolved bug in KSP. Using getAnnotation should not throw an exception when working on JS and/or native targets under these circumstances, especially when it works fine on Android/JVM targets.
