### ISSUE TITLE
NullPointExpection in ksp*Kotlin

### ISSUE THREAD

**Issue by lzb6666** [google/ksp#1501]
AGP: 4.1.0
JAVA: 11.0.18
koltin: 1.7.21
ksp:1.7.21-1.0.8
```
e: java.lang.NullPointerException
19:56:49 	at org.jetbrains.kotlin.com.intellij.util.containers.hash.LinkedHashMap$Entry.access$200(LinkedHashMap.java:283)
19:56:49 	at org.jetbrains.kotlin.com.intellij.util.containers.hash.LinkedHashMap.put(LinkedHashMap.java:127)
19:56:49 	at org.jetbrains.kotlin.com.intellij.util.containers.SLRUMap.put(SLRUMap.java:107)
19:56:49 	at org.jetbrains.kotlin.com.intellij.util.io.CompressedAppendableFile$FileChunkReadCache.put(CompressedAppendableFile.java:473)
19:56:49 	at org.jetbrains.kotlin.com.intellij.util.io.CompressedAppendableFile.saveNextChunkIfNeeded(CompressedAppendableFile.java:330)
19:56:49 	at org.jetbrains.kotlin.com.intellij.util.io.CompressedAppendableFile.append(CompressedAppendableFile.java:267)
19:56:49 	at org.jetbrains.kotlin.com.intellij.util.io.PersistentHashMapValueStorage$4.write(PersistentHashMapValueStorage.java:226)
19:56:49 	at org.jetbrains.kotlin.com.intellij.util.io.DataOutputStream.write(DataOutputStream.java:35)
19:56:49 	at org.jetbrains.kotlin.com.intellij.util.io.PersistentHashMapValueStorage.doAppendBytes(PersistentHashMapValueStorage.java:242)
19:56:49 	at org.jetbrains.kotlin.com.intellij.util.io.PersistentHashMapValueStorage.appendBytes(PersistentHashMapValueStorage.java:209)
19:56:49 	at org.jetbrains.kotlin.com.intellij.util.io.PersistentHashMapValueStorage.appendBytes(PersistentHashMapValueStorage.java:179)
19:56:49 	at org.jetbrains.kotlin.com.intellij.util.io.PersistentHashMap.doPut(PersistentHashMap.java:436)
19:56:49 	at org.jetbrains.kotlin.com.intellij.util.io.PersistentHashMap.put(PersistentHashMap.java:418)
19:56:49 	at org.jetbrains.kotlin.incremental.storage.CachingLazyStorage.set(CachingLazyStorage.kt:73)
19:56:49 	at com.google.devtools.ksp.FileToSymbolsMap.set(Incremental.kt:78)
19:56:49 	at com.google.devtools.ksp.FileToSymbolsMap.set(Incremental.kt:62)
19:56:49 	at com.google.devtools.ksp.IncrementalContext.updateCaches$update(Incremental.kt:501)
19:56:49 	at com.google.devtools.ksp.IncrementalContext.updateCaches(Incremental.kt:520)
19:56:49 	at com.google.devtools.ksp.IncrementalContext.updateCachesAndOutputs(Incremental.kt:565)
19:56:49 	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.doAnalysis(KotlinSymbolProcessingExtension.kt:338)
19:56:49 	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:124)
19:56:49 	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:100)
19:56:49 	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:265)
19:56:49 	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:53)
19:56:49 	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:115)
19:56:49 	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:256)
19:56:49 	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:99)
19:56:49 	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:58)
19:56:49 	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:158)
19:56:49 	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:53)
19:56:49 	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:99)
19:56:49 	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:47)
19:56:49 	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
19:56:49 	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1645)
19:56:49 	at jdk.internal.reflect.GeneratedMethodAccessor105.invoke(Unknown Source)
19:56:49 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
19:56:49 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
19:56:49 	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
19:56:49 	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
19:56:49 	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
19:56:49 	at java.base/java.security.AccessController.doPrivileged(Native Method)
19:56:49 	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
19:56:49 	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
19:56:49 	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
19:56:49 	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
19:56:49 	at java.base/java.security.AccessController.doPrivileged(Native Method)
19:56:49 	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
19:56:49 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
19:56:49 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
19:56:49 	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by lzb6666** [comment]
```
Failed to compute files to recompile: java.lang.NullPointerException
15:29:57 	at org.jetbrains.kotlin.com.intellij.util.containers.hash.LinkedHashMap$Entry.access$200(LinkedHashMap.java:283)
15:29:57 	at org.jetbrains.kotlin.com.intellij.util.containers.hash.LinkedHashMap.put(LinkedHashMap.java:127)
15:29:57 	at org.jetbrains.kotlin.com.intellij.util.containers.SLRUMap.put(SLRUMap.java:107)
15:29:57 	at org.jetbrains.kotlin.com.intellij.util.io.CompressedAppendableFile$FileChunkReadCache.put(CompressedAppendableFile.java:473)
15:29:57 	at org.jetbrains.kotlin.com.intellij.util.io.CompressedAppendableFile$FileChunkReadCache.get(CompressedAppendableFile.java:465)
15:29:57 	at org.jetbrains.kotlin.com.intellij.util.io.CompressedAppendableFile$SegmentedChunkInputStream.read(CompressedAppendableFile.java:515)
15:29:57 	at java.base/java.io.DataInputStream.readFully(DataInputStream.java:200)
15:29:57 	at org.jetbrains.kotlin.com.intellij.util.io.PersistentHashMapValueStorage$ReaderOverCompressedFile.get(PersistentHashMapValueStorage.java:777)
15:29:57 	at org.jetbrains.kotlin.com.intellij.util.io.PersistentHashMapValueStorage.readBytes(PersistentHashMapValueStorage.java:547)
15:29:57 	at org.jetbrains.kotlin.com.intellij.util.io.PersistentHashMap.doGet(PersistentHashMap.java:655)
15:29:57 	at org.jetbrains.kotlin.com.intellij.util.io.PersistentHashMap.get(PersistentHashMap.java:602)
15:29:57 	at org.jetbrains.kotlin.incremental.storage.CachingLazyStorage.get(CachingLazyStorage.kt:69)
15:29:57 	at org.jetbrains.kotlin.incremental.AbstractIncrementalCache$ClassFqNameToSourceMap.get(AbstractIncrementalCache.kt:195)
15:29:57 	at org.jetbrains.kotlin.incremental.AbstractIncrementalCache.getSourceFileIfClass(AbstractIncrementalCache.kt:108)
15:29:57 	at org.jetbrains.kotlin.incremental.BuildUtilKt.mapClassesFqNamesToFiles(buildUtil.kt:239)
15:29:57 	at org.jetbrains.kotlin.incremental.BuildUtilKt.mapClassesFqNamesToFiles$default(buildUtil.kt:229)
15:29:57 	at org.jetbrains.kotlin.incremental.DirtyFilesContainer.addByDirtyClasses(DirtyFilesContainer.kt:50)
15:29:57 	at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.calculateSourcesToCompileImpl(IncrementalJvmCompilerRunner.kt:303)
15:29:57 	at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.calculateSourcesToCompile(IncrementalJvmCompilerRunner.kt:200)
15:29:57 	at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.calculateSourcesToCompile(IncrementalJvmCompilerRunner.kt:126)
15:29:57 	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.tryCompileIncrementally$compile(IncrementalCompilerRunner.kt:169)
15:29:57 	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.tryCompileIncrementally(IncrementalCompilerRunner.kt:216)
15:29:57 	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:89)
15:29:57 	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.execIncrementalCompiler(CompileServiceImpl.kt:625)
15:29:57 	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.access$execIncrementalCompiler(CompileServiceImpl.kt:101)
15:29:57 	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1746)
15:29:57 	at jdk.internal.reflect.GeneratedMethodAccessor28.invoke(Unknown Source)
15:29:57 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15:29:57 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
15:29:57 	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
15:29:57 	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
15:29:57 	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
15:29:57 	at java.base/java.security.AccessController.doPrivileged(Native Method)
15:29:57 	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
15:29:57 	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
15:29:57 	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
15:29:57 	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
15:29:57 	at java.base/java.security.AccessController.doPrivileged(Native Method)
15:29:57 	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
15:29:57 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
15:29:57 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
15:29:57 	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by lzb6666** [comment]
Is there a thread safety issue here? I have more cases on similar stack.

**Comment by mikedawson** [comment]
If I were you I would try and update to the latest release first. Kotlin 1.7.21 is almost a year old and it is two major releases behind the current release (1.9.0).
