### ISSUE TITLE
exception in getJvmName for java methods

### ISSUE THREAD

**Issue by yigit** [google/ksp#164]
``` kotlin
interface MyInterface {
    val x:Int
    var y:Int
}
```
``` java
class JavaImpl implements MyInterface {
    public int getX() {
        return 1;
    }
    public int getY() {
        return 1;
    }
    public void setY(int value) {
    }
}
```

calling `getJvmName` on `getX` of `JavaImpl` causes the following exception.

```
java.lang.ClassCastException: class org.jetbrains.kotlin.load.java.descriptors.JavaForKotlinOverridePropertyDescriptor cannot 
be cast to class org.jetbrains.kotlin.descriptors.FunctionDescriptor (org.jetbrains.kotlin.load.java.descriptors.JavaForKotlinOverridePropertyDescriptor and org.jetbrains.kotlin.descriptors.FunctionDescriptor are in unnamed module of loader 'app')

	at com.google.devtools.ksp.processing.impl.ResolverImpl.resolveFunctionDeclaration(ResolverImpl.kt:345)
	at com.google.devtools.ksp.processing.impl.ResolverImpl.getJvmName(ResolverImpl.kt:516)
```

**Comment by yigit** [comment]
same exception happens when calling findOverridee in a java getter

```
class JavaImpl {
    public int getX() {
        return 1;
    }
}
```
