### ISSUE TITLE
Generating a new Kotlin class and processing it results in: `Descriptor wasn't found for declaration PRIMARY_CONSTRUCTOR`

### ISSUE THREAD

**Issue by dstepanov** [google/ksp#1695]
```
e: org.jetbrains.kotlin.resolve.lazy.NoDescriptorForDeclarationException: Descriptor wasn't found for declaration PRIMARY_CONSTRUCTOR
        at org.jetbrains.kotlin.resolve.lazy.BasicAbsentDescriptorHandler.diagnoseDescriptorNotFound(AbsentDescriptorHandler.kt:18)
        at org.jetbrains.kotlin.resolve.lazy.BasicAbsentDescriptorHandler.diagnoseDescriptorNotFound(AbsentDescriptorHandler.kt:17)
        at org.jetbrains.kotlin.resolve.lazy.LazyDeclarationResolver.resolveToDescriptor(LazyDeclarationResolver.kt:91)
        at org.jetbrains.kotlin.resolve.lazy.ResolveSession.resolveToDescriptor(ResolveSession.java:368)
        at com.google.devtools.ksp.processing.impl.ResolverImpl.resolveDeclaration(ResolverImpl.kt:497)
        at com.google.devtools.ksp.processing.impl.ResolverImpl.resolveFunctionDeclaration(ResolverImpl.kt:553)
        at com.google.devtools.ksp.processing.impl.ResolverImpl.getJvmName(ResolverImpl.kt:864)
```

Version: 1.9.10-1.0.13

**Comment by dstepanov** [comment]
After some investigation I found that the problem was with using the resolver from the previous round
