### ISSUE TITLE
NPE in Micronaut integration after updating to `1.9.22-1.0.17` 

### ISSUE THREAD

**Issue by dstepanov** [google/ksp#1696]
```
  |                           java.lang.NullPointerException	
|        |                           	at com.google.devtools.ksp.symbol.impl.kotlin.KSTypeImpl$declaration$2.invoke(KSTypeImpl.kt:62)	
|        |                           	at com.google.devtools.ksp.symbol.impl.kotlin.KSTypeImpl$declaration$2.invoke(KSTypeImpl.kt:61)	
|        |                           	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)	
|        |                           	at com.google.devtools.ksp.symbol.impl.kotlin.KSTypeImpl.getDeclaration(KSTypeImpl.kt:61)
```

https://github.com/micronaut-projects/micronaut-core/pull/10392

https://ge.micronaut.io/s/f6vnbk74hr4ny/tests/task/:inject-kotlin:test/details/io.micronaut.kotlin.processing.inject.ast.ClassElementSpec/test%20annotation%20metadata%20present%20on%20deep%20type%20parameters%20for%20field?top-execution=1

**Comment by dstepanov** [comment]
The problem was in our testing
