### ISSUE TITLE
ResolverImpl.expand broken by self referencing type args

### ISSUE THREAD

**Issue by ting-yuan** [google/ksp#1729]
Similar to #1705 

```
Exception in thread "main" java.util.concurrent.ExecutionException: com.google.devtools.kotlin.compiler.plugin.codegen.exception.KtCodegenProcessorException: exception: java.lang.StackOverflowError
	at org.jetbrains.kotlin.types.TypeSubstitutor.substituteWithoutApproximation(TypeSubstitutor.java:164)
	at org.jetbrains.kotlin.types.TypeSubstitutor.substitute(TypeSubstitutor.java:149)
	at org.jetbrains.kotlin.types.TypeSubstitutor.substitute(TypeSubstitutor.java:143)
	at org.jetbrains.kotlin.types.StarProjectionImplKt.buildStarProjectionTypeByTypeParameters(StarProjectionImpl.kt:60)
	at org.jetbrains.kotlin.types.StarProjectionImplKt.starProjectionType(StarProjectionImpl.kt:65)
	at org.jetbrains.kotlin.types.StarProjectionImpl$_type$2.invoke(StarProjectionImpl.kt:35)
	at org.jetbrains.kotlin.types.StarProjectionImpl$_type$2.invoke(StarProjectionImpl.kt:34)
	at kotlin.SafePublicationLazyImpl.getValue(LazyJVM.kt:107)
	at org.jetbrains.kotlin.types.StarProjectionImpl.get_type(StarProjectionImpl.kt:34)
	at org.jetbrains.kotlin.types.StarProjectionImpl.getType(StarProjectionImpl.kt:38)
	at com.google.devtools.ksp.processing.impl.ResolverImpl.expand(ResolverImpl.kt:680)
	at com.google.devtools.ksp.processing.impl.ResolverImpl.expand(ResolverImpl.kt:686)
	at com.google.devtools.ksp.processing.impl.ResolverImpl.expand(ResolverImpl.kt:680)
	at com.google.devtools.ksp.processing.impl.ResolverImpl.expand(ResolverImpl.kt:686)
	at com.google.devtools.ksp.processing.impl.ResolverImpl.expand(ResolverImpl.kt:680)
	at com.google.devtools.ksp.processing.impl.ResolverImpl.expand(ResolverImpl.kt:686)
```

**Comment by ting-yuan** [comment]
Would you mind giving [KSP2](https://github.com/google/ksp?tab=readme-ov-file#ksp2-is-here) a try? That is, upgrading to latest KSP or use `-Pksp.useKSP2=true` if on slightly older versions.

**Comment by cee-dee** [comment]
I'm using 
```
classpath "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin:2.1.20-1.0.32"
```
As the documentation says "Starting with KSP 2.0.0, KSP2 is enabled by default.", I should already use KSP2, right?

**Comment by ting-yuan** [comment]
2.1.20-1.0.32 still uses KSP1 by default. Can you try 2.1.20-2.0.0?

**Comment by cee-dee** [comment]
I tried to use 2.1.20-2.0.0. It gave me 
```
e: [ksp] java.lang.IllegalStateException: unexpected jvm signature V
```
A stacktrace showed that it is related to Room now (which was working with KSP1).
I could fix it by updating my Room dependencies from 2.6.1 to 2.7.1 and also updating androidx.sqlite:sqlite and androidx.sqlite:sqlite-ktx from 2.4.0. to 2.5.0.

After that, KSP2 processed my codebase without any further issues.
