### ISSUE TITLE
Unexpected descriptor type exception for `@Throws` annotation

### ISSUE THREAD

**Issue by yigit** [google/ksp#173]
For the given method:

```
@Throws(Exception::class)
protected open fun throwsException() {
}
```

Trying to call:
```
annotations.forEach {
    it.annotationType.resolve().declaration
}
```
causes 

```
java.lang.IllegalStateException: Unexpected descriptor type: class org.jetbrains.kotlin.serialization.deserialization.descriptors.DeserializedTypeAliasDescriptor, please file a bug at https://github.com/google/ksp/issues/new

	at com.google.devtools.ksp.processing.impl.ResolverImpl.findDeclaration(ResolverImpl.kt:461)
	at com.google.devtools.ksp.symbol.impl.kotlin.KSTypeImpl$declaration$2.invoke(KSTypeImpl.kt:47)
	at com.google.devtools.ksp.symbol.impl.kotlin.KSTypeImpl$declaration$2.invoke(KSTypeImpl.kt:31)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.google.devtools.ksp.symbol.impl.kotlin.KSTypeImpl.getDeclaration(KSTypeImpl.kt)
```

**Comment by neetopia** [comment]
Actually this is pretty interesting bug, if you import `Throws` annotation explicitly with `import kotlin.jvm.Throws` this won't cause issue.
