### ISSUE TITLE
KSP task (non-)registration happens too soon

### ISSUE THREAD

**Issue by ZacSweers** [google/ksp#1789]
I have a gradle plugin that tries to conditionally enable KSP and add relevant KSP processors to it. However, I found that KSP's task registration can be unintentionally deleted by a simple `project.afterEvaluate` in gradle, resulting in the task never being registered and thus not run.

Example

```kotlin
// in build.gradle.kts, or a gradle plugin

project.afterEvaluate {
  if (enableKsp) {
    pluginManager.apply("com.google.devtools.ksp")

    dependencies.add("ksp", "some.ksp:processor:1.0.0")
  }
}
```

will result in KSP being applied but no `ksp*Kotlin` task ever being registered and thus never running. If I add any dependency to the `ksp` configuration (even one without any KSP processors in it), it works and picks up the later-added dependency too.

I think I would expect this to always register the KSP task, then conditionally no-op at task-action-time rather than try to conditionally avoid adding the task.

**Comment by ZacSweers** [comment]
Sorry it looks like this is actually after two `afterEvaluate` calls, not just one level. Which is admittedly a somewhat edge case :). That said, still would be nice if there was a way to defer this to task-time instead

**Comment by ZacSweers** [comment]
This has come to a head in AGP 8.10.0, which now fully blocks KSP from being applied in an afterEvaluate, more or less preventing conditionally applying it in a convention plugin

```
Caused by: java.lang.RuntimeException: It is too late to call addKspConfigurations as the callbacks already executed.	
at com.android.build.api.extension.impl.OperationsRegistrar.addInternalOperation(OperationsRegistrar.kt:82)	
at com.android.build.api.extension.impl.OperationsRegistrar.addInternalOperation$default(OperationsRegistrar.kt:76)	
at com.android.build.api.extension.impl.AndroidComponentsExtensionImpl.addSourceSetConfigurations(AndroidComponentsExtensionImpl.kt:353)	
at com.android.build.api.extension.impl.AndroidComponentsExtensionImpl.addKspConfigurations(AndroidComponentsExtensionImpl.kt:148)	
at com.google.devtools.ksp.gradle.KspConfigurations$3.invoke(KspConfigurations.kt:108)	
at com.google.devtools.ksp.gradle.KspConfigurations$3.invoke(KspConfigurations.kt:104)	
at com.google.devtools.ksp.gradle.KspConfigurations._init_$lambda$5(KspConfigurations.kt:104)	
at org.gradle.api.internal.plugins.DefaultPluginManager$2.execute(DefaultPluginManager.java:261)	
at org.gradle.api.internal.plugins.DefaultPluginManager$2.execute(DefaultPluginManager.java:258)	
at org.gradle.internal.code.DefaultUserCodeApplicationContext$CurrentApplication$1.execute(DefaultUserCodeApplicationContext.java:124)	
at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction$1.run(DefaultCollectionCallbackActionDecorator.java:110)	
at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:30)	
at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:27)	
at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:67)	
at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:60)	
at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:167)	
at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:60)	
at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:48)	
at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction.execute(DefaultCollectionCallbackActionDecorator.java:107)	
at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:185)	
at org.gradle.api.internal.plugins.DefaultPluginManager.withPlugin(DefaultPluginManager.java:264)	
at com.google.devtools.ksp.gradle.KspConfigurations.<init>(KspConfigurations.kt:104)	
at com.google.devtools.ksp.gradle.KspGradleSubplugin.apply(KspSubplugin.kt:220)	
at com.google.devtools.ksp.gradle.KspGradleSubplugin.apply(KspSubplugin.kt:80)	
at org.gradle.api.internal.plugins.ImperativeOnlyPluginTarget.applyImperative(ImperativeOnlyPluginTarget.java:55)	
at org.gradle.api.internal.plugins.RuleBasedPluginTarget.applyImperative(RuleBasedPluginTarget.java:51)	
at org.gradle.api.internal.plugins.DefaultPluginManager.addPlugin(DefaultPluginManager.java:190)	
at org.gradle.api.internal.plugins.DefaultPluginManager.access$100(DefaultPluginManager.java:54)	
at org.gradle.api.internal.plugins.DefaultPluginManager$AddPluginBuildOperation.run(DefaultPluginManager.java:285)	
at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:30)	
at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:27)	
at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:67)	
at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:60)	
at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:167)	
at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:60)	
at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:48)	
at org.gradle.api.internal.plugins.DefaultPluginManager.lambda$doApply$0(DefaultPluginManager.java:170)	
at org.gradle.internal.code.DefaultUserCodeApplicationContext.apply(DefaultUserCodeApplicationContext.java:44)	
at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:169)	
at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:148)	
at foundry.gradle.FoundryExtension$applyTo$1.execute(FoundryExtension.kt:283)
```

**Comment by Enaium** [comment]
The issue still exists in `2.2.0-2.0.2`

`kspKotlin` task will be skipped when I declare ksp in `afterEvaluate`

```kotlin
afterEvaluate {
    dependencies {
        ksp("x:y:z")
    }
}
```

![Image](https://github.com/user-attachments/assets/f726de58-94d6-4747-bfae-f3093c94d3f1)
