### ISSUE TITLE
Out of memory errors while migrating from kapt to ksp

### ISSUE THREAD

**Issue by ankur2136** [google/ksp#1922]
I am trying to migrate our multi-module android project to ksp. The build works fine locally (on 2021 M1 Max) but fails consistently on github runners with different errors each time. 

Most recent error 
```
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':ui:ScreenCuration:compileSystemDebugUnitTestKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > java.lang.reflect.InvocationTargetException

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org./
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':ui:ScreenAppDetails:compileSystemDebugUnitTestKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Not enough memory to run compilation.  Try to increase it via 'gradle.properties':
     org.gradle.jvmargs=-Xmx<size>
 ```
 
 ```
 The root cause java.lang.OutOfMemoryError was thrown at: unknown
	at org.jetbrains.kotlin.codegen.TransformationMethodVisitor.visitEnd(TransformationMethodVisitor.kt:89)
	at org.jetbrains.org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:772)
	at org.jetbrains.kotlin.backend.jvm.codegen.CoroutineCodegenKt.acceptWithStateMachine(CoroutineCodegen.kt:72)
	at org.jetbrains.kotlin.backend.jvm.codegen.ClassCodegen.generateMethod(ClassCodegen.kt:427)
	at org.jetbrains.kotlin.backend.jvm.codegen.ClassCodegen.generate(ClassCodegen.kt:169)
	at org.jetbrains.kotlin.backend.jvm.codegen.ExpressionCodegen.visitClass(ExpressionCodegen.kt:967)
	at org.jetbrains.kotlin.backend.jvm.codegen.ExpressionCodegen.visitClass(ExpressionCodegen.kt:134)
	at org.jetbrains.kotlin.ir.declarations.IrClass.accept(IrClass.kt:73)
	at org.jetbrains.kotlin.backend.jvm.codegen.ExpressionCodegen.visitStatementContainer(ExpressionCodegen.kt:562)
	at org.jetbrains.kotlin.backend.jvm.codegen.ExpressionCodegen.visitContainerExpression(ExpressionCodegen.kt:576)
	at org.jetbrains.kotlin.backend.jvm.codegen.ExpressionCodegen.visitContainerExpression(ExpressionCodegen.kt:134)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitor$DefaultImpls.visitBlock(IrElementVisitor.kt:192)
	at org.jetbrains.kotlin.backend.jvm.codegen.ExpressionCodegen.visitBlock(ExpressionCodegen.kt:396)
	at org.jetbrains.kotlin.backend.jvm.codegen.ExpressionCodegen.visitBlock(ExpressionCodegen.kt:134)
	at org.jetbrains.kotlin.ir.expressions.IrBlock.accept(IrBlock.kt:20)
	at org.jetbrains.kotlin.backend.jvm.codegen.ExpressionCodegen.gen(ExpressionCodegen.kt:205)
	at org.jetbrains.kotlin.backend.jvm.codegen.IrCallGenerator.genValueAndPut(IrCallGenerator.kt:48)
	at org.jetbrains.kotlin.backend.jvm.codegen.ExpressionCodegen.visitCall$handleValueParameter(ExpressionCodegen.kt:606)
	at org.jetbrains.kotlin.backend.jvm.codegen.ExpressionCodegen.visitCall(ExpressionCodegen.kt:619)
	at org.jetbrains.kotlin.backend.jvm.codegen.ExpressionCodegen.visitCall(ExpressionCodegen.kt:134)
	at org.jetbrains.kotlin.ir.expressions.IrCall.accept(IrCall.kt:26)
	at org.jetbrains.kotlin.backend.jvm.codegen.ExpressionCodegen.visitReturn(ExpressionCodegen.kt:1018)
	at org.jetbrains.kotlin.backend.jvm.codegen.ExpressionCodegen.visitReturn(ExpressionCodegen.kt:134)
	at org.jetbrains.kotlin.ir.expressions.IrReturn.accept(IrReturn.kt:26)
	at org.jetbrains.kotlin.backend.jvm.codegen.ExpressionCodegen.visitStatementContainer(ExpressionCodegen.kt:562)
	at org.jetbrains.kotlin.backend.jvm.codegen.ExpressionCodegen.visitBlockBody(ExpressionCodegen.kt:567)
	at org.jetbrains.kotlin.backend.jvm.codegen.ExpressionCodegen.visitBlockBody(ExpressionCodegen.kt:134)
	at org.jetbrains.kotlin.ir.expressions.IrBlockBody.accept(IrBlockBody.kt:25)
	at org.jetbrains.kotlin.backend.jvm.codegen.ExpressionCodegen.generate(ExpressionCodegen.kt:228)
	at org.jetbrains.kotlin.backend.jvm.codegen.FunctionCodegen.doGenerate(FunctionCodegen.kt:122)
	at org.jetbrains.kotlin.backend.jvm.codegen.FunctionCodegen.generate(FunctionCodegen.kt:47)
	... 42 more
Caused by: java.lang.OutOfMemoryError: Metaspace


FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':ui:ScreenCuration:compileSystemDebugUnitTestKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > java.lang.reflect.InvocationTargetException

 ```
 
 Here is my configurations 
 ```
 gradle.properties
 
 org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=2g -XX:+HeapDumpOnOutOfMemoryError -XX:+UseParallelGC -Dfile.encoding=UTF-8
```

```
versions 

androidxComposeCompiler = "1.5.14"
androidGradlePlugin = "8.4.1"
kotlin = "1.9.24"
ksp = "1.9.24-1.0.20"
```

This is my replacement 
```
plugins {
    kotlin("kapt")
}
```

is replaced with 
```
plugins {
    alias(libs.plugins.ksp)
}
```

```
    kapt(libs.androidx.hiltAndroidXCompiler)
    kapt(libs.google.hiltCompiler)
    kaptTest(libs.test.hiltTestingCompiler)
    kapt(libs.androidx.roomCompiler)
    kapt(libs.moshi.moshiKotlinCodegen)
    kapt {
            arguments {
                arg("room.schemaLocation", "$projectDir/schemas")
            }
    }
```

is replaced by 
```
    ksp(libs.androidx.hiltAndroidXCompiler)
    ksp(libs.google.hiltCompiler)
    kspTest(libs.test.hiltTestingCompiler)
    ksp(libs.androidx.roomCompiler)
    ksp(libs.moshi.moshiKotlinCodegen)
    ksp {
            arg("room.schemaLocation", "$projectDir/schemas")
        }
```        

job configuration on github runner

```
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Copy CI gradle.properties
      run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

    - name: Gradle cache
      uses: gradle/actions/setup-gradle@v3

 ... 
```

**Comment by yuroyami** [comment]
Would the issue persist even when using ? [`ksp2`](https://github.com/google/ksp/blob/main/docs/ksp2.md)

**Comment by ting-yuan** [comment]
The OOM happened in a Kotlin compilation in [KotlinCompileDaemon](https://kotlinlang.org/docs/gradle-compilation-and-caches.html#kotlin-daemon-jvmargs-property) rather than Gradle daemon. You may try putting this in gradle.properties:

```
kotlin.daemon.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=2g
```

Or [configure it in Kotlin extension](https://kotlinlang.org/docs/gradle-compilation-and-caches.html#kotlin-extension).

Because this doesn't look like a KSP issue, I'm closing it for now. Feel free to reopen it if none of those configurations work.

**Comment by vitusortner** [comment]
@ankur2136 were you able to resolve the issue? We're running into something very similar and bumping the heap and metaspace size didn't help on our end.

**Comment by ankur2136** [comment]
I was able to finally make it work on `2.0.0-1.0.21` with `org.gradle.jvmargs=-Xmx6g -XX:MaxMetaspaceSize=4g`

**Comment by yanjiepeng** [comment]
> 我终于可以让它继续工作`2.0.0-1.0.21`了`org.gradle.jvmargs=-Xmx6g -XX:MaxMetaspaceSize=4g`

Hi ankur, Did you solve your problem completely?  I had the same problem but configuring -XX:MaxMetaspaceSize had no effect
