### ISSUE TITLE
"KSTypeArgument.type should not have been null, please file a bug. STAR null" with KSP2.0.0-1.0.22 and KSP2

### ISSUE THREAD

**Issue by lwasyl** [google/ksp#1957]
```java
 java.lang.IllegalStateException: KSTypeArgument.type should not have been null, please file a bug. STAR null
        at dagger.spi.internal.shaded.androidx.room.compiler.processing.ksp.KSTypeExtKt.requireType(KSTypeExt.kt:128)
        at dagger.spi.internal.shaded.androidx.room.compiler.processing.ksp.KspTypeArgumentType.<init>(KspTypeArgumentType.kt:41)
        at dagger.spi.internal.shaded.androidx.room.compiler.processing.ksp.KspTypeArgumentType.<init>(KspTypeArgumentType.kt:33)
        at dagger.spi.internal.shaded.androidx.room.compiler.processing.ksp.KspProcessingEnv.wrap(KspProcessingEnv.kt:280)
        at dagger.spi.internal.shaded.androidx.room.compiler.processing.ksp.KspType$typeArguments$2.invoke(KspType.kt:202)
        at dagger.spi.internal.shaded.androidx.room.compiler.processing.ksp.KspType$typeArguments$2.invoke(KspType.kt:198)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at dagger.spi.internal.shaded.androidx.room.compiler.processing.ksp.KspType.getTypeArguments(KspType.kt:198)
        at dagger.internal.codegen.base.DaggerSuperficialValidation.validateType(DaggerSuperficialValidation.java:337)
        ... 53 more
```

This happens when processing this file:
```kotlin
import androidx.lifecycle.ViewModel
import androidx.lifecycle.ViewModelProvider
import javax.inject.Inject
import javax.inject.Provider

class ViewModelFactory @Inject constructor(
    private val creators: Map<Class<*>, @JvmSuppressWildcards Provider<ViewModel>>,
) : ViewModelProvider.Factory {

    @Suppress("UNCHECKED_CAST")
    override fun <T : ViewModel> create(modelClass: Class<T>): T = creators[modelClass]?.get() as T
}
```

Kotlin 2.0.0 + KSP2.0.0-1.0.22 (`ksp.useKSP2=true`) + Dagger 2.51.1.

**Comment by neetopia** [comment]
It looks an expected behavior to me, STAR projection should not have a type since it is literally a `*` at the use site, cc @kuanyingchou should this be taken care of this behavior change? 

reference: https://github.com/google/ksp/blob/main/docs/ksp2api.md#type-arguments-of-star-projections

**Comment by kuanyingchou** [comment]
Yes, I'm working on [a change in XProcessing](https://android-review.googlesource.com/c/platform/frameworks/support/+/3045215) for this, but please note that [Dagger doesn't work with KSP2 yet](https://github.com/google/dagger/issues/4303#issuecomment-2100469486).

**Comment by mobibob** [comment]
> Yes, I'm working on [a change in XProcessing](https://android-review.googlesource.com/c/platform/frameworks/support/+/3045215) for this, but please note that [Dagger doesn't work with KSP2 yet](https://github.com/google/dagger/issues/4303#issuecomment-2100469486).

This has convinced me to give up on using Hilt.  Too temperamental and impossible to troubleshoot even when using AI companions (I used both Gemini and CoPilot).  I also took an online CBT class for training.

**Comment by GabeK0** [comment]
+1, updating hilt and dagger to 2.56.2 fixed this for me as well

**Comment by Hardik-Vaghani** [comment]
**In your "libs.versions.toml" file!**

[versions]
agp = "8.9.3"
hiltAndroid = "2.56.2"
kotlin = "2.1.21"
ksp = "2.1.21-2.0.1"

[libraries]
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hiltAndroid" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hiltAndroid" } # ✅ fixed
google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

**Comment by Rifqips** [comment]
[versions]
accompanistSystemuicontroller = "0.36.0"
datastorePreferences = "1.1.7"
coreKtx = "1.16.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
library = "4.2.0"
libraryNoOp = "4.2.0"
lifecycleRuntimeKtx = "2.9.2"
activityCompose = "1.10.1"
composeBom = "2024.09.00"
material3Version = "1.3.2"
retrofit = "2.9.0"
okhttp = "4.12.0"
gson = "2.10.1"
hilt = "2.57"
hiltNavigationCompose = "1.2.0"
navigationCompose = "2.7.7"
material3 = "1.2.1"
kotlin = "2.2.0"
ksp = "2.2.0-2.0.2"
agp = "8.6.0"

**Comment by deepgulhane3** [comment]
Want will be the room supported version ?
