### ISSUE TITLE
[KSP2] IllegalArgumentException while calling asMemberOf on property of a value class

### ISSUE THREAD

**Issue by kuanyingchou** [google/ksp#1989]
Calling asMemberOf on property declared in value classes leads to exception.

Repro: https://github.com/google/ksp/commit/c479699ecb463c303deca4ae33a5ce8c9847542d

Exception:

```
java.lang.IllegalArgumentException: MyValueClass? is not a sub type of the class/interface that contains `s` (MyValueClass)
	at com.google.devtools.ksp.impl.ResolverAAImpl.computeAsMemberOf$kotlin_analysis_api(ResolverAAImpl.kt:852)
	at com.google.devtools.ksp.impl.symbol.kotlin.KSPropertyDeclarationImpl.asMemberOf(KSPropertyDeclarationImpl.kt:160)
	at com.google.devtools.ksp.processor.AsMemberOfProcessor.process(AsMemberOfProcessor.kt:27)
	at com.google.devtools.ksp.impl.KotlinSymbolProcessing.execute(KotlinSymbolProcessing.kt:537)
	at com.google.devtools.ksp.test.AbstractKSPAATest.runTest(AbstractKSPAATest.kt:136)
...
```

**Comment by solcott** [comment]
Any update on this?  This is blocking our update to K2.
