### ISSUE TITLE
[KSP2] Not yet implemented: KSValueArgumentLiteImpl.getLocation

### ISSUE THREAD

**Issue by kuanyingchou** [google/ksp#2048]
Created the issue so it's easier to track.

Stacktrace:

```
Caused by: kotlin.NotImplementedError: An operation is not implemented: Not yet implemented
	at com.google.devtools.ksp.impl.symbol.java.KSValueArgumentLiteImpl.getLocation(KSValueArgumentLiteImpl.kt:28)
	at androidx.room.compiler.processing.ksp.KspMessager.onPrintMessage(KspMessager.kt:53)
	at androidx.room.compiler.processing.XMessager.printMsg(XMessager.kt:98)
	at androidx.room.compiler.processing.XMessager.printMessage(XMessager.kt:87)
	at androidx.room.compiler.processing.XMessagerTest$errorOnAnnotationValueTest$1.invoke(XMessagerTest.kt:208)
...
```

**Comment by ting-yuan** [comment]
Fixed in #2050
