### ISSUE TITLE
[KSP2] command line fails with `KaInvalidLifetimeOwnerAccessException` if `-jdk-home` is missing

### ISSUE THREAD

**Issue by joffrey-bion** [google/ksp#2064]
When calling KSP without `-jdk-home` argument, I get the following:

```
Exception in thread "main" org.jetbrains.kotlin.analysis.api.lifetime.KaInvalidLifetimeOwnerAccessException: Access to invalid org.jetbrains.kotlin.analysis.api.platform.lifetime.KotlinAlwaysAccessibleLifetimeToken@16745ba7: PSI has changed since creation
        at org.jetbrains.kotlin.analysis.api.fir.utils.ValidityAwareCachedValue.getValue-impl(ValidityAwareCachedValue.kt:33)
        at org.jetbrains.kotlin.analysis.api.fir.types.KaFirUsualClassType.getAnnotations(KaFirUsualClassType.kt:53)
        at com.google.devtools.ksp.impl.symbol.kotlin.UtilKt.annotations(util.kt:318)
        at com.google.devtools.ksp.impl.symbol.kotlin.UtilKt.annotations$default(util.kt:317)
        at com.google.devtools.ksp.impl.symbol.kotlin.KSTypeImpl.getAnnotations(KSTypeImpl.kt:92)
        at androidx.room.compiler.processing.ksp.KspPrimitiveType.<init>(KspPrimitiveType.kt:35)
        at androidx.room.compiler.processing.ksp.KspArrayType$Factory.<init>(KspArrayType.kt:119)
        at androidx.room.compiler.processing.ksp.KspProcessingEnv.getArrayTypeFactory(KspProcessingEnv.kt:129)
        at androidx.room.compiler.processing.ksp.KspProcessingEnv.wrap(KspProcessingEnv.kt:327)
        at androidx.room.compiler.processing.ksp.KspProcessingEnv.wrap(KspProcessingEnv.kt:295)
        at androidx.room.compiler.processing.ksp.KspPrimitiveType.boxed(KspPrimitiveType.kt:47)
        at androidx.room.compiler.processing.ksp.KspPrimitiveType.boxed(KspPrimitiveType.kt:32)
        at androidx.room.solver.types.BoxedPrimitiveColumnTypeAdapter$Companion.createBoxedPrimitiveAdapters(BoxedPrimitiveColumnTypeAdapter.kt:33)
        at androidx.room.solver.TypeAdapterStore$Companion.create(TypeAdapterStore.kt:182)
        at androidx.room.processor.Context$typeAdapterStore$2.invoke(Context.kt:57)
        at androidx.room.processor.Context$typeAdapterStore$2.invoke(Context.kt:53)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at androidx.room.processor.Context.getTypeAdapterStore(Context.kt:53)
        at androidx.room.processor.Context.collectLogs(Context.kt:169)
        at androidx.room.DatabaseProcessingStep.process(DatabaseProcessingStep.kt:68)
        at androidx.room.compiler.processing.CommonProcessorDelegate.processLastRound(XBasicAnnotationProcessor.kt:168)
        at androidx.room.compiler.processing.ksp.KspBasicAnnotationProcessor.runLastRound(KspBasicAnnotationProcessor.kt:81)
        at androidx.room.compiler.processing.ksp.KspBasicAnnotationProcessor.finish(KspBasicAnnotationProcessor.kt:73)
        at com.google.devtools.ksp.impl.KotlinSymbolProcessing.execute(KotlinSymbolProcessing.kt:584)
        at com.google.devtools.ksp.cmdline.KSPJvmMainKt.runWithArgs(KSPJvmMain.kt:45)
        at com.google.devtools.ksp.cmdline.KSPJvmMain$Companion.main(KSPJvmMain.kt:20)
        at com.google.devtools.ksp.cmdline.KSPJvmMain.main(KSPJvmMain.kt)
```

If the JDK home argument is mandatory, it would be nice to eagerly fail when parsing CLI arguments, like for the other ones.

**Comment by stevdza-san** [comment]
I'm also getting this error while trying to run my app:

**Kotlin: 2.0.20
KSP: 2.0.20-1.0.25**

```
[ksp] ksp.org.jetbrains.kotlin.analysis.api.lifetime.KaInvalidLifetimeOwnerAccessException: Access to invalid ksp.org.jetbrains.kotlin.analysis.api.platform.lifetime.KotlinAlwaysAccessibleLifetimeToken@1e6ff208: PSI has changed since creation
```

**Comment by eygraber** [comment]
I'm getting that error regardless of whether `-jdk-home` is missing or not.

**Comment by ting-yuan** [comment]
Would anyone mind sharing a repro case? Specifically,
1. KSP version
2. Kotlin version
3. full command line arguments
4. sources to be processed
5. processor jars
