### ISSUE TITLE
`java.lang.IllegalStateException: Storage for [...] is already registered` with 2.0.20-1.0.24

### ISSUE THREAD

**Issue by ychescale9** [google/ksp#2072]
Since updating to `2.0.20-1.0.24` our devs started getting the following occasionally:

```
java.lang.IllegalStateException: Storage for [path/to/project/my-module/build/kspCaches/debug/symbolLookups/id-to-file.tab] is already registered
	at org.jetbrains.kotlin.com.intellij.util.io.FilePageCache.registerPagedFileStorage(FilePageCache.java:410)
	at org.jetbrains.kotlin.com.intellij.util.io.PagedFileStorage.<init>(PagedFileStorage.java:72)
	at org.jetbrains.kotlin.com.intellij.util.io.ResizeableMappedFile.<init>(ResizeableMappedFile.java:55)
	at org.jetbrains.kotlin.com.intellij.util.io.PersistentBTreeEnumerator.<init>(PersistentBTreeEnumerator.java:128)
	at org.jetbrains.kotlin.com.intellij.util.io.PersistentEnumerator.createDefaultEnumerator(PersistentEnumerator.java:52)
	at org.jetbrains.kotlin.com.intellij.util.io.PersistentMapImpl.<init>(PersistentMapImpl.java:165)
	at org.jetbrains.kotlin.com.intellij.util.io.PersistentMapImpl.<init>(PersistentMapImpl.java:140)
	at org.jetbrains.kotlin.com.intellij.util.io.PersistentMapBuilder.buildImplementation(PersistentMapBuilder.java:88)
	at org.jetbrains.kotlin.com.intellij.util.io.PersistentMapBuilder.build(PersistentMapBuilder.java:71)
	at org.jetbrains.kotlin.com.intellij.util.io.PersistentHashMap.<init>(PersistentHashMap.java:45)
	at org.jetbrains.kotlin.com.intellij.util.io.PersistentHashMap.<init>(PersistentHashMap.java:71)
	at org.jetbrains.kotlin.incremental.storage.LazyStorage.createMap(LazyStorage.kt:60)
	at org.jetbrains.kotlin.incremental.storage.LazyStorage.getStorageOrCreateNew(LazyStorage.kt:57)
	at org.jetbrains.kotlin.incremental.storage.LazyStorage.set(LazyStorage.kt:78)
	at org.jetbrains.kotlin.incremental.storage.PersistentStorageWrapper.set(PersistentStorage.kt:94)
	at org.jetbrains.kotlin.incremental.LookupStorage.addFileIfNeeded(LookupStorage.kt:165)
	at org.jetbrains.kotlin.incremental.LookupStorage.addAll$lambda$4(LookupStorage.kt:117)
	at org.jetbrains.kotlin.utils.CollectionsKt.keysToMap(collections.kt:117)
	at org.jetbrains.kotlin.incremental.LookupStorage.addAll(LookupStorage.kt:117)
	at org.jetbrains.kotlin.incremental.BuildUtilKt.update(buildUtil.kt:134)
	at com.google.devtools.ksp.LookupStorageWrapperImpl.update(IncrementalContext.kt:231)
	at com.google.devtools.ksp.common.IncrementalContextBase.updateLookupCache(IncrementalContextBase.kt:133)
	at com.google.devtools.ksp.common.IncrementalContextBase.updateCaches(IncrementalContextBase.kt:364)
	at com.google.devtools.ksp.common.IncrementalContextBase.updateCachesAndOutputs(IncrementalContextBase.kt:470)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.doAnalysis(KotlinSymbolProcessingExtension.kt:362)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:112)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:75)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze$lambda$12(KotlinToJVMBytecodeCompiler.kt:373)
	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:112)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:364)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.repeatAnalysisIfNeeded(KotlinToJVMBytecodeCompiler.kt:282)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.runFrontendAndGenerateIrUsingClassicFrontend(KotlinToJVMBytecodeCompiler.kt:195)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:106)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:170)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:43)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:103)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:49)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1555)
	at jdk.internal.reflect.GeneratedMethodAccessor92.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
	Suppressed: java.lang.Exception: Storage[path/to/project/my-module/build/kspCaches/debug/symbolLookups/id-to-file.tab] registration stack trace
		at org.jetbrains.kotlin.com.intellij.util.io.FilePageCache.registerPagedFileStorage(FilePageCache.java:437)
		at org.jetbrains.kotlin.com.intellij.util.io.PagedFileStorage.<init>(PagedFileStorage.java:72)
		at org.jetbrains.kotlin.com.intellij.util.io.ResizeableMappedFile.<init>(ResizeableMappedFile.java:55)
		at org.jetbrains.kotlin.com.intellij.util.io.PersistentBTreeEnumerator.<init>(PersistentBTreeEnumerator.java:128)
		at org.jetbrains.kotlin.com.intellij.util.io.PersistentEnumerator.createDefaultEnumerator(PersistentEnumerator.java:52)
		at org.jetbrains.kotlin.com.intellij.util.io.PersistentMapImpl.<init>(PersistentMapImpl.java:165)
		at org.jetbrains.kotlin.com.intellij.util.io.PersistentMapImpl.<init>(PersistentMapImpl.java:140)
		at org.jetbrains.kotlin.com.intellij.util.io.PersistentMapBuilder.buildImplementation(PersistentMapBuilder.java:88)
		at org.jetbrains.kotlin.com.intellij.util.io.PersistentMapBuilder.build(PersistentMapBuilder.java:71)
		at org.jetbrains.kotlin.com.intellij.util.io.PersistentHashMap.<init>(PersistentHashMap.java:45)
		at org.jetbrains.kotlin.com.intellij.util.io.PersistentHashMap.<init>(PersistentHashMap.java:71)
		at org.jetbrains.kotlin.incremental.storage.LazyStorage.createMap(LazyStorage.kt:60)
		at org.jetbrains.kotlin.incremental.storage.LazyStorage.getStorageIfExists(LazyStorage.kt:51)
		at org.jetbrains.kotlin.incremental.storage.LazyStorage.get(LazyStorage.kt:74)
		at org.jetbrains.kotlin.incremental.storage.PersistentStorageWrapper.get(PersistentStorage.kt:90)
		at org.jetbrains.kotlin.incremental.LookupStorage.get(LookupStorage.kt:99)
		at com.google.devtools.ksp.LookupStorageWrapperImpl.get(IncrementalContext.kt:224)
		at com.google.devtools.ksp.common.IncrementalContextBase.calcDirtyFiles(IncrementalContextBase.kt:234)
		at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$2.invoke(KotlinSymbolProcessingExtension.kt:196)
		at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$2.invoke(KotlinSymbolProcessingExtension.kt:189)
		at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.handleException(KotlinSymbolProcessingExtension.kt:414)
		at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.doAnalysis(KotlinSymbolProcessingExtension.kt:189)
		at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:112)
		at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:75)
		at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze$lambda$12(KotlinToJVMBytecodeCompiler.kt:373)
		at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:112)
		at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:364)
		... 24 more
```

Our workaround has been killing the Kotlin daemons.

Others have experienced the same issue as [reported](https://slack-chats.kotlinlang.org/t/22942553/i-m-getting-this-error-when-working-with-2-0-20-rc2-1-0-24-o) in the kotlinlang slack.

There are reports on both Android and JS projects so doesn't look like it's specific to a target.

We're still on KSP 1.

**Comment by AkobirBozorov** [comment]
I am getting this error as well. I managed to put ksp and hilt in my project and now this error. I don't know what to do as i am new developer

**Comment by palsega** [comment]
What I would do is use a tested version, for me it was 2.0.10-1.0.24

**Comment by metinyildiran** [comment]
I've got Room in my project and version 2.0.10-1.0.24 with Kotlin version 2.0.10 also worked for me.

**Comment by mohsen2986** [comment]
> I've got Room in my project and version 2.0.10-1.0.24 with Kotlin version 2.0.10 also worked for me.

It works for me

**Comment by demidenko** [comment]
got this exception after incorrect (or unfinished) automigration in android room. after define manual migration it throw this on build
downgrade to kotlin=2.0.10 and ksp=2.0.10-1.0.24 works fine

**Comment by epool** [comment]
for those who face this issue, killing the Kotlin daemons workaround from [Slack](https://kotlinlang.slack.com/archives/C013BA8EQSE/p1724263710418299?thread_ts=1724248309.540349&cid=C013BA8EQSE) worked for me:
```
jps | grep -E 'KotlinCompileDaemon' | awk '{print $1}' | xargs kill -9 || true
```

**Comment by Kevinrob** [comment]
> for those who face this issue, killing the Kotlin daemons workaround from [Slack](https://kotlinlang.slack.com/archives/C013BA8EQSE/p1724263710418299?thread_ts=1724248309.540349&cid=C013BA8EQSE) worked for me:
> 
> ```
> jps | grep -E 'KotlinCompileDaemon' | awk '{print $1}' | xargs kill -9 || true
> ```

Or just `/gradlew --stop` 👍

**Comment by ting-yuan** [comment]
Looks similar to #2042, where `kspCache` is left in an illegal state. Let's see if this persists after the fix to #2042 has landed.

**Comment by ting-yuan** [comment]
KSP 2.0.20-1.0.25 is just released and may have fixed this issue. Would you mind to give it a try?

**Comment by thejufo** [comment]
> KSP 2.0.20-1.0.25 is just released and may have fixed this issue. Would you mind to give it a try?

Unfortunately, I can confirm that the issue still persists

**Comment by ychescale9** [comment]
sorry, re-opened

**Comment by metinyildiran** [comment]
> KSP 2.0.20-1.0.25 is just released and may have fixed this issue. Would you mind to give it a try?

It fixed the issue for me. I've cleaned the project and tried with Koltin version 2.0.20.

**Comment by palsega** [comment]
I noticed before it was an issue but now I confirm that with version 2.0.20-1.0.25 everything works. Just rebuilding the project even without its cleaning.

**Comment by alxgord** [comment]
I confirm that after updating ksp to 2.0.20-1.0.25 and invalidating the cache the build was successful

**Comment by hoangchungk53qx1** [comment]
after updating ksp to 2.0.20-1.0.25 , it works , try to delete build folder and rebuilding the project

**Comment by bitspittle** [comment]
@ychescale9 looks like people are saying it's resolved for them, so maybe it's ok to close it after all!

Fwiw I've been using latest KSP since yesterday without issue, although I never used the previous version that people were complaining about so I wasn't 100% sure if my experience mattered.

**Comment by asapha** [comment]
It still happens when compiling after a processor raised an exception.
Repro if it helps:

```bash
# A project with a sample using its own processor
git clone https://github.com/r0adkll/kimchi.git
cd kimchi

# Add invalid code from the processor's point of view
echo "@com.r0adkll.kimchi.annotations.ContributesBinding(com.r0adkll.kimchi.restaurant.common.scopes.AppScope::class) object Test" > sample/desktopApp/src/main/kotlin/com/r0adkll/kimchi/restaurant/di/Test.kt`

# The processor raises its error 
# (here `e: [ksp] KimchiException: Bound implementation must have a single supertype, or specify a 'boundType' if extending more than one supertype.`)
`./gradlew :sample:desktopApp:run`

# Remove the "invalid" code
`rm sample/desktopApp/src/main/kotlin/com/r0adkll/kimchi/restaurant/di/Test.kt`

# The storage error is raised, the kotlin daemon needs to be killed.
`./gradlew :sample:desktopApp:run`
```

**Comment by polivmi1** [comment]
What worked for us is to also kill the daemon (found this in a slack discussion)
jps | grep -E 'KotlinCompileDaemon' | awk '{print $1}' | xargs kill -9 || true

**Comment by bamsbamx** [comment]
I am also suffering this with version 2.0.20-1.0.25. In my case using androidx Room in a KMP project. Seems like it starts to throw after a build error happened. For example, I had a non-suspending function in my database DAO, in KMP, Room requires all functions to be suspending,  so it threw an error whem building. After that the error mentioned in this issue started to happen.

However, after restarting the IDE (Android Studio) it was fixed

**Comment by rnett** [comment]
This can be avoided more permanently by disabling the Gradle daemon, e.g. by adding `org.gradle.daemon=false` to your `gradle.properties` file. It does have a significant performance penalty though.

**Comment by nico-gonzalez** [comment]
> I am also suffering this with version 2.0.20-1.0.25. In my case using androidx Room in a KMP project. Seems like it starts to throw after a build error happened. For example, I had a non-suspending function in my database DAO, in KMP, Room requires all functions to be suspending, so it threw an error whem building. After that the error mentioned in this issue started to happen.
> 
> However, after restarting the IDE (Android Studio) it was fixed

same here while changing some classes that caused recompilation of several modules, it's still happening with `2.0.20-1.0.25`. In my case doing a `./gradlew --stop` fixed it

**Comment by galex** [comment]
We're also suffering from this in `20.0.20-1.0.24`
```
> Task :project:features:repo:kspDebugKotlin FAILED
e: java.nio.file.NoSuchFileException: /.../build/kspCaches/debug/backups/java/byRounds/2/com/project/board/dataSource
```

```
e: java.lang.IllegalStateException: Storage for [/.../build/kspCaches/debug/symbolLookups/id-to-file.tab] is already registered
```
The only solution I've found is to stop the Gradle Daemon to be able to recover.

In `20.0.20-1.0.25` the second one still happens but a running the build task again seems to work for now.

**Comment by rjaros** [comment]
Still an issue for me on `2.0.20-1.0.25` as well.

**Comment by LloydBlv** [comment]
This was really a nasty one, changed so many things until I decided to Google and found this thread..

**Comment by kevogabaa** [comment]
This thread is a blessing in disguise. `jps | grep -E 'KotlinCompileDaemon' | awk '{print $1}' | xargs kill -9 || true` worked for me too.

**Comment by ZacSweers** [comment]
This does still happen on 2.0.20-1.0.25 unfortunately

**Comment by ansman** [comment]
Do you all use file system watching?

**Comment by IceBlizz6** [comment]
> Do you all use file system watching?

I'm using IntelliJ (probably same as many others here).
It's possible that this editor is doing some file system watching without my knowledge.
It is rich with many features so it wouldn't surprise me.

But i don't think i have set up any additional system that would use file system watching, atleast not to my knowledge.

**Comment by ansman** [comment]
I'm specifically talking about [Gradle file system watching](https://docs.gradle.org/current/userguide/file_system_watching.html)

**Comment by IceBlizz6** [comment]
> Gradle enables file system watching by default for supported operating systems since Gradle 7.

Says that it is enabled by default since Gradle 7 and i'm using 8 so i believe answer is yes in my case atleast.

**Comment by enriqueajin** [comment]
> got this exception after incorrect (or unfinished) automigration in android room. after define manual migration it throw this on build downgrade to kotlin=2.0.10 and ksp=2.0.10-1.0.24 works fine

Worked perfectly for me. Thanks!

**Comment by asapha** [comment]
I could repro the issue via some integrations tests:
https://github.com/google/ksp/compare/main...asapha:ksp:issue-2072 ([repo](https://github.com/asapha/ksp/tree/issue-2072))
One uses an external processor (`kotlin-inject`) and the other uses a custom one.

Feel free to remix/take inspiration from them

**Comment by sonrohan** [comment]
We are also seeing this issue.

**Comment by NicosNicolaou16** [comment]
I have the same issue with the version 2.0.20-1.0.25

**Comment by aboutZZ** [comment]
Please stop spamming this issue

**Comment by NicosNicolaou16** [comment]
> Worked on version 2.0.20-1.0.25
> 
> 1. Run:
> 
> > jps | grep -E 'KotlinCompileDaemon' | awk '{print $1}' | xargs kill -9 || true
> 
> 2. Invalidate Cache and Restart
> 3. Run your app

Thank you worked!

**Comment by NicosNicolaou16** [comment]
@raquezha yes worked but I changed something on Room Database again reproduce this error, so I'm fixing this issue with "git stash". I did the steps that you wrote on the comment again but not working again

**Comment by ychescale9** [comment]
@ting-yuan given the scale of the impact are we planning to do a release with the fix soon?

**Comment by hgarciaalberto** [comment]
Same issue on `2.0.21-1.0.25` `Storage for [.../app/build/kspCaches/miviaDebug/symbolLookups/id-to-file.tab] is already registered`

**Comment by ting-yuan** [comment]
2.0.21-1.0.26, which contains the fix, was just released!

**Comment by sarimmehdi** [comment]
I am using the latest 2.0.21-1.0.26 version and I still get this error after modifying one of the Type Converters for the Room Database

**Comment by cfa532** [comment]
Had the same error. Look it up at stackoverflow. This worked for me.

Added it to gradle.properties file
ksp.incremental=false

**Comment by MohamedHarmoush** [comment]
Had the same error. the fix was stop the current the gradle daemons using `./gradlew --stop`
solution link> https://stackoverflow.com/a/79042629/13321079

**Comment by solonovamax** [comment]
> 2.0.21-1.0.26, which contains the fix, was just released!

Would it be possible to get a fix pushed for `2.0.20` as well?
currently, I want to stay on `2.0.20` as I'm developing a gradle plugin, and the gradle release I'm targetting uses that kotlin version.

**Comment by azattech** [comment]
`ksp.incremental=false`

add this to `gradle.properties` file

it worked for me. After got build I removed it and reworked again.

**Comment by issamux** [comment]
> Or just `./gradlew --stop` 👍

solved the problem thanks.
