### ISSUE TITLE
Java implementation of a kotlin interface triggers illegal state exception when accessing properties

### ISSUE THREAD

**Issue by yigit** [google/ksp#216]
For the given code:

```kotlin
interface MyInterface {
    var x:Int
}
```

```java
class JavaImpl implements MyInterface {
    public int getX() {
        return 1;
    }
    public void setX(int value) {
    }
}
```

Trying to get properties of the `JavaImpl` class declaration causes an exception:

```
val javaClass = invocation.kspResolver.getClassDeclarationByName("JavaImpl")!!
javaClass.getAllProperties()
```

```
unexpected psi: class org.jetbrains.kotlin.com.intellij.psi.impl.source.PsiMethodImpl
java.lang.IllegalStateException: unexpected psi: class org.jetbrains.kotlin.com.intellij.psi.impl.source.PsiMethodImpl
	at com.google.devtools.ksp.symbol.impl.UtilsKt.toKSPropertyDeclaration(utils.kt:278)
	at com.google.devtools.ksp.symbol.impl.java.KSClassDeclarationJavaImpl.getAllProperties(KSClassDeclarationJavaImpl.kt:94)
```

**Comment by ting-yuan** [comment]
The fix will be available in next release, scheduled on Jan. 6.
