### ISSUE TITLE
[ksp] java.lang.IllegalStateException: unexpected jvm signature V

### ISSUE THREAD

**Issue by Rafael2616** [google/ksp#2177]
when upgrading to ksp 2.1.0-Beta2-1.0.26 im having this issue in every build so im unable to compile my app due to it. i have the ksp.UseKSP2=true enabled in my gradle properties

```
[ksp] java.lang.IllegalStateException: unexpected jvm signature V
````
ps: is an Android only project

the build works normally in all versions below it.

**Comment by jonamireh** [comment]
+1, I'm also running into this issue. Here's the relevant stacktrace:

```
Caused by: java.lang.IllegalStateException: unexpected jvm signature V
        at androidx.room.compiler.processing.javac.kotlin.JvmDescriptorUtilsKt.typeNameFromJvmSignature(JvmDescriptorUtils.kt:106)
        at androidx.room.compiler.processing.ksp.KSTypeJavaPoetExtKt.asJTypeName(KSTypeJavaPoetExt.kt:100)
        at androidx.room.compiler.processing.ksp.KSTypeJavaPoetExtKt.asJTypeName(KSTypeJavaPoetExt.kt:165)
        at androidx.room.compiler.processing.ksp.KSTypeJavaPoetExtKt.asJTypeName(KSTypeJavaPoetExt.kt:155)
        at androidx.room.compiler.processing.ksp.DefaultKspType.resolveJTypeName(DefaultKspType.kt:43)
        at androidx.room.compiler.processing.ksp.KspType$xTypeName$2.invoke(KspType.kt:90)
        at androidx.room.compiler.processing.ksp.KspType$xTypeName$2.invoke(KspType.kt:69)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:83)

```

For more context, there is a Room DAO class written in Kotlin and does not declare a return type. So something like:

```
@Delete
suspend fun delete(entity: Entity)
```

Room [is asking KSP for the JVM signature](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:room/room-compiler-processing/src/main/java/androidx/room/compiler/processing/ksp/KSTypeJavaPoetExt.kt;l=102-105). KSP [is presumably returning](https://github.com/google/ksp/blob/579c9daf5227d736520b9bbd07dd5de962e9f138/kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/ResolverAAImpl.kt#L751) `V` for void because the return type is `kotlin.Unit` but Room [doesn't seem to parse that](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:room/room-compiler-processing/src/main/java/androidx/room/compiler/processing/javac/kotlin/JvmDescriptorUtils.kt;l=64-108), causing this error

**Comment by jonamireh** [comment]
This has been fixed in [Room 2.7.0-alpha11](https://developer.android.com/jetpack/androidx/releases/room#2.7.0-alpha11)

**Comment by Rafael2616** [comment]
Thanks, i'll update now and confirm that is fixed and close the issue

**Comment by amal** [comment]
We have lots of these errors from Dagger when using `ksp.UseKSP2=true`

```
e: [ksp] dagger.internal.codegen.base.DaggerSuperficialValidation$ValidationException$UnexpectedException: 
  Validation trace:
    => element (CLASS): app.PostViewModel

> Task :kspDebugKotlin FAILED
e: [ksp] dagger.internal.codegen.base.DaggerSuperficialValidation$ValidationException$UnexpectedException: 
  Validation trace:
    => element (CLASS): app.NewViewModel

...
```
