### ISSUE TITLE
Unsupported operation exception when getting location on a class declaration

### ISSUE THREAD

**Issue by yigit** [google/ksp#251]
repro CL:
https://github.com/yigit/ksp/commit/f8f51d68dca154ef220641e829a6bf6bc47dca3b

when trying to get location on a property, it throws exception.

```
java.lang.UnsupportedOperationException
	at com.intellij.psi.impl.PsiDocumentManagerBase.associatePsi(PsiDocumentManagerBase.java:114)
	at com.intellij.psi.impl.PsiDocumentManagerBase.getDocument(PsiDocumentManagerBase.java:180)
	at com.google.devtools.ksp.symbol.impl.UtilsKt.toLocation(utils.kt:188)
	at com.google.devtools.ksp.symbol.impl.kotlin.KSDeclarationImpl$location$2.invoke(KSDeclarationImpl.kt:31)
	at com.google.devtools.ksp.symbol.impl.kotlin.KSDeclarationImpl$location$2.invoke(KSDeclarationImpl.kt:27)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.google.devtools.ksp.symbol.impl.kotlin.KSDeclarationImpl.getLocation(KSDeclarationImpl.kt)
	at c
```

```
class ClassInMain {
    val prop1: String = TODO()
    val prop2: String? = TODO()
    fun fun1(): String = TODO()
    fun fun2() :String = TODO()
}
```

I just hit this while trying to repro #250 so please ignore the unrelated stuff in the PR.

**Comment by yigit** [comment]
this might actually be a test only problem, i noticed we don't have any tests that query the location.
