### ISSUE TITLE
The latest version is not compatible with Android plugin

### ISSUE THREAD

**Issue by Kr328** [google/ksp#305]
I just added the android build plugin to the playground in the release, it got

```
...
Caused by: org.gradle.api.UnknownDomainObjectException: Extension of type 'CommonExtension' does not exist. Currently registered extension types: [ExtraPropertiesExtension, KspExtension]
	at org.gradle.internal.extensibility.ExtensionsStorage.getHolderByType(ExtensionsStorage.java:88)
	at org.gradle.internal.extensibility.ExtensionsStorage.configureExtension(ExtensionsStorage.java:70)
	at org.gradle.internal.extensibility.DefaultConvention.configure(DefaultConvention.java:189)
	at org.gradle.internal.extensibility.DefaultConvention.configure(DefaultConvention.java:184)
	at com.google.devtools.ksp.gradle.AndroidPluginIntegration.decorateAndroidExtension(AndroidPluginIntegration.kt:60)
...
```

The modified playground project:
[playground-android.zip](https://github.com/google/ksp/files/5959489/playground-android.zip)

Environment:
 - JDK: openjdk-1.8
 - OS: ArchLinux
 - Android Plugin: 4.0.2/4.2.0-beta02
 - Kotlin: 1.4.30
 - KSP: 1.4.30-1.0.0-alpha02

**Comment by yigit** [comment]
i've not checked your sample yet but i'm surprised, we are literally using 4.2.0-beta02 in our tests:

https://github.com/google/ksp/blob/master/gradle.properties#L5

**Comment by yigit** [comment]
not sure what is going on yet but when i bump the android plugin version (and also use the version from the plugin declaration), i get the following error:

```
java.lang.NoClassDefFoundError: com/android/build/gradle/BaseExtension
        at org.jetbrains.kotlin.gradle.plugin.mpp.SyncKotlinAndAndroidSourceSetsKt.syncKotlinAndAndroidSourceSets(syncKotlinAndAndroidSourceSets.kt:22)
        at org.jetbrains.kotlin.gradle.plugin.AbstractAndroidProjectHandler.configureTarget(KotlinPlugin.kt:780)
        at org.jetbrains.kotlin.gradle.plugin.KotlinAndroidPlugin$Companion.applyToTarget(KotlinPlugin.kt:743)
        at org.jetbrains.kotlin.gradle.plugin.KotlinAndroidPlugin.apply(KotlinPlugin.kt:705)
        at org.jetbrains.kotlin.gradle.plugin.KotlinAndroidPlugin.apply(KotlinPlugin.kt:694)
        at org.jetbrains.kotlin.gradle.plugin.KotlinBasePluginWrapper.apply(KotlinPluginWrapper.kt:104)
```

**Comment by yigit** [comment]
I'm not sure what happened in that sample but when i clean it up to set all plugins from settings.gradle, it works fine:

```
pluginManagement {
    val kotlinVersion: String by settings
    val kspVersion: String by settings
    val agpVersion: String by settings
    plugins {
        id("com.google.devtools.ksp") version kspVersion apply false
        kotlin("jvm") version kotlinVersion apply false
        kotlin("android") version kotlinVersion apply false
        id("com.android.application") version agpVersion apply false
    }
    repositories {
        gradlePluginPortal()
        google()
    }
}
```
[ksp-with-android.tar.gz](https://github.com/google/ksp/files/5962912/ksp-with-android.tar.gz)

**Comment by Kr328** [comment]
> I'm not sure what happened in that sample but when i clean it up to set all plugins from settings.gradle, it works fine:
> 
> ```
> pluginManagement {
>     val kotlinVersion: String by settings
>     val kspVersion: String by settings
>     val agpVersion: String by settings
>     plugins {
>         id("com.google.devtools.ksp") version kspVersion apply false
>         kotlin("jvm") version kotlinVersion apply false
>         kotlin("android") version kotlinVersion apply false
>         id("com.android.application") version agpVersion apply false
>     }
>     repositories {
>         gradlePluginPortal()
>         google()
>     }
> }
> ```
> 
> [ksp-with-android.tar.gz](https://github.com/google/ksp/files/5962912/ksp-with-android.tar.gz)

Thanks, everything work fine now
