### ISSUE TITLE
build failure due to "Descriptor wasn't found for declaration CLASS"

### ISSUE THREAD

**Issue by neetopia** [google/ksp#427]
related reproduce: https://github.com/ZacSweers/MoshiX/pull/107

**Comment by neetopia** [comment]
Tried to reproduce on Windnows/Linux, seems not reproducable there, only reproducable on Mac. 

The root cause for this is the compiler not able to find the descriptor for a class, while resolution has been successful, it is not retrieved from BindingContext (retrieving resolved descriptor from bindingContext is a common practice in Kotlin compiler), therefore causing this exception. I am not sure why this is Mac specific though.

@ZacSweers Can you try to reproduce this on the latest version? I was working on a quite old branch(already deleted on your repo so I backed up that in my [fork](https://github.com/neetopia/MoshiX/tree/z/updates)), I am not sure if CI is failing for the same reason, since in my repo it is failing with a [different error message](https://github.com/neetopia/MoshiX/runs/2618417864), and given CI is using Ubuntu and I've seen it working on multiple Linux distros (unfortunately Ubuntu is not one among them..), quite odd it will be failing for Ubuntu.

**Comment by ZacSweers** [comment]
> I am not sure why this is Mac specific though.

FWIW the CI linked in the original repro is on Linux. I'll try with beta01

**Comment by ZacSweers** [comment]
Unfortunately still happens with beta01. You can reproduce by removing the `@Ignore` annotations on the `MoshiSealedSymbolProcessorProviderTest` and `JsonClassSymbolProcessorTest` classes in the linked project's `main` branch

**Comment by neetopia** [comment]
Tried removing comment and running in CI it seems they are [passing except one](https://github.com/neetopia/MoshiX/actions/runs/914297374) run for JDK13.

I tried debugging into compiler, the root cause here is while resolution was successful, the key `ktClassOrObject` of the resolved descriptor was changed when recording the descriptors into bindingcontext, therefore causing the lookup failure. This only happens after alpha09 and the only possible offending change between alpha08 and alpha09 is actually a version bump in the Kotlin compiler itself. I will need more time to debug into compiler to see how it only fails for Mac.

**Comment by darvld** [comment]
I've run into the same issue on Mac but only when using library kotlin-compile-testing. Running the processor normally doesn't fail. In fact, even when the issue takes place (in one of my test cases) the KSP processor actually works as expected, but the error is reported. Any workarounds for this?

**Comment by neetopia** [comment]
That's interesting finding, let me try to look into kotlin-compile-testing to see if anything wrong.

**Comment by darvld** [comment]
I did some more research and it seems the problem is caused due to some interaction between ksp, kotlin-compile-testing and kotlinpoet.  I've managed to create a somewhat simple reproducer (at least it fails on my machine). You can see the source in [this gist](https://gist.github.com/darvld/8a27c159fd02aa6222137ff804185a0c). Before you can use it, add the dependencies specified at the start of the file (kotlin-compile-testing, kotlinpoet and the ksp API).

**Comment by alexvanyo** [comment]
I'm running into what appears to be a very similar issue on the latest  while introducing KSP to `sealed-enum`:
https://github.com/livefront/sealed-enum/pull/76

Via GitHub Actions CI, some 45 tests are always failing for `macos-latest` and `windows-latest` builds, but are passing in `ubuntu-latest`.

In particular, these are the tests where I'm using `kotlin-compile-testing` with `KSP` to check the compilation of the generated code. It looks like my conditions match the behavior observed above, where I'm using `KotlinPoet` to generate the code.

**Comment by ZacSweers** [comment]
I'm able to get a little farther now in a recent release, but now see this issue

```
e: java.lang.IllegalArgumentException: Missing extension point: org.jetbrains.kotlin.com.intellij.psi.treeChangeListener in container org.jetbrains.kotlin.com.intellij.mock.MockProject@7dd4403d
	at org.jetbrains.kotlin.com.intellij.openapi.extensions.impl.ExtensionsAreaImpl.getExtensionPoint(ExtensionsAreaImpl.java:260)
	at org.jetbrains.kotlin.com.intellij.openapi.extensions.BaseExtensionPointName.getPointImpl(BaseExtensionPointName.java:28)
	at org.jetbrains.kotlin.com.intellij.openapi.extensions.ProjectExtensionPointName.getExtensions(ProjectExtensionPointName.java:37)
	at org.jetbrains.kotlin.com.intellij.psi.impl.PsiManagerImpl.fireEvent(PsiManagerImpl.java:350)
	at org.jetbrains.kotlin.com.intellij.psi.impl.PsiManagerImpl.beforePropertyChange(PsiManagerImpl.java:249)
	at org.jetbrains.kotlin.com.intellij.psi.impl.file.impl.FileManagerImpl.firePropertyChangedForUnloadedPsi(FileManagerImpl.java:148)
	at org.jetbrains.kotlin.com.intellij.openapi.application.WriteAction.run(WriteAction.java:102)
	at org.jetbrains.kotlin.com.intellij.psi.impl.PsiManagerImpl.dropPsiCaches(PsiManagerImpl.java:87)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.doAnalysis(KotlinSymbolProcessingExtension.kt:111)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:120)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:86)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:540)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:531)
	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:113)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:531)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.repeatAnalysisIfNeeded(KotlinToJVMBytecodeCompiler.kt:501)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:188)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:154)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:169)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:52)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:90)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:44)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:98)
	at com.tschuchort.compiletesting.AbstractKotlinCompilation.compileKotlin(AbstractKotlinCompilation.kt:184)
	at com.tschuchort.compiletesting.KotlinCompilation.compileJvmKotlin(KotlinCompilation.kt:469)
	at com.tschuchort.compiletesting.KotlinCompilation.compile(KotlinCompilation.kt:645)
	at dev.zacsweers.moshix.sealed.codegen.ksp.MoshiSealedSymbolProcessorProviderTest.smokeTest
```

**Comment by ZacSweers** [comment]
and after updating KSP to 1.4.3 I'm back at the original issue

**Comment by artem-zinnatullin** [comment]
Stumbled upon this issue in a new KSP project right when I added 2 tests using `kotlin-compile-testing`.

My KSP does not generate any code, just validates it. Once I added 2nd test — test run failed on second test with `Descriptor wasn't found for declaration PROPERTY`. 

However if I run tests separately, both are passing.

It seems that some compiler state is kept in memory between tests and breaks the type resolution.

Env:

- macOS 12.3.1, M1
- Open JDK 17.0.1
- `com.github.tschuchortdev:kotlin-compile-testing` and `com.github.tschuchortdev:kotlin-compile-testing-ksp` 1.4.8
- `com.google.devtools.ksp:symbol-processing-api` 1.6.21-1.0.5

**Comment by neetopia** [comment]
This involves third party test framework and probably KSP can't do much. Can you try to use different inputs for tests (maybe just some minor naming difference) to see if this issue goes away? The cause here is mostly incorrectly reused PSIs and should go away when content changes.

**Comment by artem-zinnatullin** [comment]
So, I found what was causing this in my setup. I've copied `build.gradle`s from another project of mine where I had JUnit5 configured for parallel test execution 🤦 🤦 

I was showing my wife "Here is why I hate programming, look" and she was like "So they fail when they run in parallel?" Haven't even occurred to me that I had them running in non-sequential order, heh.

```kotlin
// Run separate test classes within a module in parallel.
systemProperty("junit.jupiter.execution.parallel.enabled", "true")
// Multiply CPU cores x2
systemProperty("junit.jupiter.execution.parallel.config.dynamic.factor", "2")
// Run separate tests in same class in parallel.
systemProperty("junit.jupiter.execution.parallel.mode.default", "concurrent")
```

On the other hand, it's bad that `kotlin-compile-testing` or KSP or kotlinc does not work in parallel environment, would be nice to avoid global mutable state.
