### ISSUE TITLE
Calling KSPLogger.error on java 11 throws java.lang.IllegalStateException: Should not be called!

### ISSUE THREAD

**Issue by BartArys** [google/ksp#434]
The following code will throw an IllegalStateException

```kotlin
class Processor(
    private val generator: CodeGenerator,
    private val logger: KSPLogger,
) : SymbolProcessor {

    override fun process(resolver: Resolver): List<KSAnnotated> {
        logger.error("message")

        return emptyList()
    }

}
```

output:
```
e: [ksp] message
e: java.lang.IllegalStateException: Should not be called!
        at org.jetbrains.kotlin.types.ErrorUtils$1.getPackage(ErrorUtils.java:95)
        at org.jetbrains.kotlin.descriptors.DescriptorUtilKt.resolveClassByFqName(descriptorUtil.kt:25)
        at org.jetbrains.kotlin.resolve.checkers.ExperimentalUsageChecker$Companion.checkCompilerArguments$checkAnnotation(ExperimentalUsageChecker.kt:258)
        at org.jetbrains.kotlin.resolve.checkers.ExperimentalUsageChecker$Companion.checkCompilerArguments(ExperimentalUsageChecker.kt:281)
        at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:113)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:505)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:189)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:155)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:169)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:52)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:88)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:44)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:98)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1575)
        at jdk.internal.reflect.GeneratedMethodAccessor103.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

Removing `logger.error("message")` fixes the issue.

KSP version: 1.5.0-1.0.0-alpha10
Kotlin version: 1.5.0
Java version: 
openjdk 11.0.2 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)

This might be related to a similar issue KAPT was facing in 1.3.50: <https://youtrack.jetbrains.com/issue/KT-33617>

**Comment by neetopia** [comment]
#578 is a tentative fix, should be available after 1.5.30 release.

**Comment by ting-yuan** [comment]
`logger.error(...)` is designed to fail the processing / compilation. The Gradle task is expected to fail.

The exception is not expected but harmless. It is thrown when the compiler tries to resolve the annotations specified by the `-Xexperimental=...` compiler argument, in a wrong context after compilation.

Given that
1. The exception is harmless, albeit confusing.
2. The `-Xexerimental` compiler is going away in 1.6.0. It's not reproducible in 1.6.0.
3. A workaround in KSP is possible, but requires larger change and can be risky.

Let's lowering the priority for this issue.

**Comment by ting-yuan** [comment]
BTW, KAPT showed the same stack trace because it also suffers from the same issue in compiler's cleaning up. The linked issue was resolved by fixing the reason failing the compilation. When KAPT fails for some other reason (e.g., logger.error()) and when `-Xexperimental=some-non-default-annotation` exists, the same stack trace will pop up again.
