### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by pvegh** [google/ksp#452]
e: java.lang.NoSuchMethodError: 'java.util.List com.google.devtools.ksp.processing.Resolver$DefaultImpls.getSymbolsWithAnnotation$default(com.google.devtools.ksp.processing.Resolver, java.lang.String, boolean, int, java.lang.Object)'
	at androidx.room.compiler.processing.XProcessingStep$DefaultImpls.executeInKsp(XProcessingStep.kt:72)
	at androidx.room.DatabaseProcessingStep.executeInKsp(DatabaseProcessingStep.kt:34)
	at androidx.room.RoomKspProcessor.process(RoomKspProcessor.kt:56)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$4$1.invoke(KotlinSymbolProcessingExtension.kt:164)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$4$1.invoke(KotlinSymbolProcessingExtension.kt:163)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.handleException(KotlinSymbolProcessingExtension.kt:241)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.doAnalysis(KotlinSymbolProcessingExtension.kt:163)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:119)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:85)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:514)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:505)
	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:112)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:505)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:189)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:155)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:169)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:52)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:88)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:44)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:98)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1575)

**Comment by aasitnikov** [comment]
I stumbled upon this issue, when I forgot to change the version processor was built with:

```
// processor/build.gradle.kts
dependencies {
    implementation("com.google.devtools.ksp:symbol-processing-api:1.4.32-1.0.0-alpha08")
}

// root build.gradle
buildscript {
    dependencies {
        classpath "com.google.devtools.ksp:symbol-processing-gradle-plugin:1.5.0-1.0.0-alpha09"
    }
}
```

Fix is quite simple - make sure to use the same version in processor and plugin

**Comment by pvegh** [comment]
I don't have different versions, using alpha10 everywhere

**Comment by ting-yuan** [comment]
The returning type of `getSymbolsWithAnnotation` was changed from `List` to `Sequence` in alpha09 -> alpha10. It looks like the Room version is compiled with pre-alpha10 KSP. Can you try to upgrade Room?

**Comment by ting-yuan** [comment]
Did you have a chance to try with newer Room?

**Comment by pvegh** [comment]
Seems to work in combination with latest beta of KSP and latest room release (2.3.0 IIRC).
