### ISSUE TITLE
RuntimeException: cannot find implementation for Database_Impl

### ISSUE THREAD

**Issue by itsandreramon** [google/ksp#471]
After upgrading KSP to 1.5.10 from 1.4.32, I got the following error when using Room:

```
Caused by: java.lang.RuntimeException: cannot find implementation for de.thb.core.data.AppDatabase. AppDatabase_Impl does not exist
	at androidx.room.Room.getGeneratedImplementation(Room.java:97)
	at androidx.room.RoomDatabase$Builder.build(RoomDatabase.java:1486)
```

My Instrumentation Tests also fail because of this, and after I went back to kapt, everything worked again.

**Comment by ting-yuan** [comment]
Can you try upgrading Room as well? There are API changes from 1.4.32 to 1.5.10 and therefore older Room version won't work with newer KSP.

**Comment by itsandreramon** [comment]
Oh I forgot. I'm on the latest Room version 2.4.0-alpha02

**Comment by RyuNen344** [comment]
I'm facing same error, because of ksp does not generate code. 👀 
kotlin **1.5.21**, gradle **7.0.2**, agp **7.0.0**, room **2.3.0**, ksp **1.5.21-1.0.0-beta06**

**Comment by ting-yuan** [comment]
Would you mind to share build logs? `./gradlew --info` would be best, but if not open source project, anything would be helpful.

**Comment by ting-yuan** [comment]
BTW, room 2.3.0 does not work with ksp 1.5.21-1.0.0-beta06, because it was built with ksp 1.4.30-1.0.0-alpha04 and there had been some API changes that made them incompatible. Could you try room 2.4.0-alpha04?

**Comment by RyuNen344** [comment]
>room 2.3.0 does not work with ksp 1.5.21-1.0.0-beta06, because it was built with ksp 1.4.30-1.0.0-alpha04

sorry, i didn't know that ksp has no compatibility.

ok, i will try it and make text of ```./gradlew --info```

**Comment by ting-yuan** [comment]
There was no compatibility in alpha releases. Hopefully it's less painful now in beta :)
