### ISSUE TITLE
NPE when trying to get arguments of KSAnnotation 

### ISSUE THREAD

**Issue by popovanton0** [google/ksp#512]
I applied this annotation
```kotlin
annotation class Ann(
    val property: KClass<out CharSequence> = String::class
)
```
without explicitly specifying value of the `property`:
```kotlin
@Ann
fun Switch() {
    // impl
}
```
and when trying to get a list of `KSAnnotation.arguments` got this exception:
```
e: [ksp] java.lang.NullPointerException
	at org.jetbrains.kotlin.resolve.constants.evaluate.ConstantExpressionEvaluatorVisitor.visitClassLiteralExpression(ConstantExpressionEvaluator.kt:878)
	at org.jetbrains.kotlin.resolve.constants.evaluate.ConstantExpressionEvaluatorVisitor.visitClassLiteralExpression(ConstantExpressionEvaluator.kt:370)
	at org.jetbrains.kotlin.psi.KtClassLiteralExpression.accept(KtClassLiteralExpression.kt:23)
	at org.jetbrains.kotlin.resolve.constants.evaluate.ConstantExpressionEvaluatorVisitor.evaluate(ConstantExpressionEvaluator.kt:383)
	at org.jetbrains.kotlin.resolve.constants.evaluate.ConstantExpressionEvaluator.evaluateExpression(ConstantExpressionEvaluator.kt:285)
	at org.jetbrains.kotlin.resolve.constants.evaluate.ConstantExpressionEvaluator.evaluateToConstantValue(ConstantExpressionEvaluator.kt:297)
	at com.google.devtools.ksp.processing.impl.ResolverImpl.evaluateConstant(ResolverImpl.kt:358)
	at com.google.devtools.ksp.symbol.impl.binary.KSAnnotationDescriptorImplKt.getDefaultValue(KSAnnotationDescriptorImpl.kt:131)
	at com.google.devtools.ksp.symbol.impl.binary.KSAnnotationDescriptorImplKt.getAbsentDefaultArguments(KSAnnotationDescriptorImpl.kt:119)
	at com.google.devtools.ksp.symbol.impl.binary.KSAnnotationDescriptorImplKt.createKSValueArguments(KSAnnotationDescriptorImpl.kt:109)
	at com.google.devtools.ksp.symbol.impl.kotlin.KSAnnotationImpl$arguments$2.invoke(KSAnnotationImpl.kt:45)
	at com.google.devtools.ksp.symbol.impl.kotlin.KSAnnotationImpl$arguments$2.invoke(KSAnnotationImpl.kt:44)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.google.devtools.ksp.symbol.impl.kotlin.KSAnnotationImpl.getArguments(KSAnnotationImpl.kt:44)
```

Also, if type of the `property` is an `Array` or a subclass of `Annotation`, `KSValueArgument.value` returns null.
So, what is the general status of support for default values of annotation classes?

**Comment by neetopia** [comment]
This is a known issue #53 , we will fix it.

**Comment by popovanton0** [comment]
Should I close this issue then?

**Comment by neetopia** [comment]
Sure, closing as duplicate.
