### ISSUE TITLE
KSAnnotated#arguments causes an NPE

### ISSUE THREAD

**Issue by AlexBeggs** [google/ksp#538]
The KSAnnotation.arguments throws an NPE when one of the arguments is a KClass.
If a default is defined but doesn't define one in the declaration. 

See branch code example

The call that throws an NPE

https://github.com/AlexBeggs/ksp/commit/bd4b66b35cae566d44b7449296b2b22126978940#diff-99a569b02956aecc148c7b198d7b3d5b083f664c795bd6e35deb141c067b041bR31

The definition of the annotation with the KClass

https://github.com/AlexBeggs/ksp/commit/bd4b66b35cae566d44b7449296b2b22126978940#diff-9fd74f2bedbcd4b782c13de9fe99cc8b1bda160f1461aab4713c315b9c81e1b2R33

`
error: [ksp] java.lang.NullPointerException
	at org.jetbrains.kotlin.resolve.constants.evaluate.ConstantExpressionEvaluatorVisitor.visitClassLiteralExpression(ConstantExpressionEvaluator.kt:937)
	at org.jetbrains.kotlin.resolve.constants.evaluate.ConstantExpressionEvaluatorVisitor.visitClassLiteralExpression(ConstantExpressionEvaluator.kt:373)
	at org.jetbrains.kotlin.psi.KtClassLiteralExpression.accept(KtClassLiteralExpression.kt:23)
	at org.jetbrains.kotlin.resolve.constants.evaluate.ConstantExpressionEvaluatorVisitor.evaluate(ConstantExpressionEvaluator.kt:389)
	at org.jetbrains.kotlin.resolve.constants.evaluate.ConstantExpressionEvaluator.evaluateExpression(ConstantExpressionEvaluator.kt:288)
	at org.jetbrains.kotlin.resolve.constants.evaluate.ConstantExpressionEvaluator.evaluateExpression$default(ConstantExpressionEvaluator.kt:281)
	at org.jetbrains.kotlin.resolve.constants.evaluate.ConstantExpressionEvaluator.evaluateToConstantValue(ConstantExpressionEvaluator.kt:300)
	at com.google.devtools.ksp.processing.impl.ResolverImpl.evaluateConstant(ResolverImpl.kt:370)
	at com.google.devtools.ksp.symbol.impl.binary.KSAnnotationDescriptorImplKt.getDefaultValue(KSAnnotationDescriptorImpl.kt:258)
	at com.google.devtools.ksp.symbol.impl.binary.KSAnnotationDescriptorImplKt.getAbsentDefaultArguments(KSAnnotationDescriptorImpl.kt:145)
	at com.google.devtools.ksp.symbol.impl.binary.KSAnnotationDescriptorImplKt.createKSValueArguments(KSAnnotationDescriptorImpl.kt:135)
	at com.google.devtools.ksp.symbol.impl.kotlin.KSAnnotationImpl$arguments$2.invoke(KSAnnotationImpl.kt:45)
	at com.google.devtools.ksp.symbol.impl.kotlin.KSAnnotationImpl$arguments$2.invoke(KSAnnotationImpl.kt:44)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.google.devtools.ksp.symbol.impl.kotlin.KSAnnotationImpl.getArguments(KSAnnotationImpl.kt:44)
	at com.google.devtools.ksp.processor.GetSymbolsFromAnnotationProcessor.addAnnotations(GetSymbolsFromAnnotationProcessor.kt:31)
	at com.google.devtools.ksp.processor.GetSymbolsFromAnnotationProcessor.process(GetSymbolsFromAnnotationProcessor.kt:20)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$4$1.invoke(KotlinSymbolProcessingExtension.kt:165)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$4$1.invoke(KotlinSymbolProcessingExtension.kt:164)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.handleException(KotlinSymbolProcessingExtension.kt:242)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.doAnalysis(KotlinSymbolProcessingExtension.kt:164)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:120)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:86)
	at org.jetbrains.kotlin.resolve.lazy.JvmResolveUtil.analyze(JvmResolveUtil.kt:99)
	at org.jetbrains.kotlin.resolve.lazy.JvmResolveUtil.analyzeAndCheckForErrors(JvmResolveUtil.kt:66)
	at org.jetbrains.kotlin.codegen.GenerationUtils.compileFilesUsingStandardMode(GenerationUtils.kt:158)
	at org.jetbrains.kotlin.codegen.GenerationUtils.compileFiles(GenerationUtils.kt:82)
	at org.jetbrains.kotlin.codegen.GenerationUtils.compileFiles(GenerationUtils.kt:67)
	at org.jetbrains.kotlin.codegen.GenerationUtils.compileFiles$default(GenerationUtils.kt:61)
	at com.google.devtools.ksp.test.AbstractKotlinKSPTest.compileModule(AbstractKotlinKSPTest.kt:145)
	at com.google.devtools.ksp.test.AbstractKotlinKSPTest.doMultiFileTest(AbstractKotlinKSPTest.kt:81)
	at org.jetbrains.kotlin.test.KotlinBaseTest.doTest(KotlinBaseTest.kt:31)
	at org.jetbrains.kotlin.test.KotlinTestUtils.lambda$testWithCustomIgnoreDirective$5(KotlinTestUtils.java:577)
	at org.jetbrains.kotlin.test.KotlinTestUtils.runTestImpl(KotlinTestUtils.java:547)
	at org.jetbrains.kotlin.test.KotlinTestUtils.runTest(KotlinTestUtils.java:490)
	at com.google.devtools.ksp.test.KotlinKSPTestGenerated.runTest(KotlinKSPTestGenerated.java:37)
	at com.google.devtools.ksp.test.KotlinKSPTestGenerated.testGetSymbolsFromAnnotation(KotlinKSPTestGenerated.java:162)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at org.jetbrains.kotlin.test.testFramework.KtUsefulTestCase.lambda$runTest$9(KtUsefulTestCase.java:373)
	at org.jetbrains.kotlin.test.testFramework.KtUsefulTestCase.lambda$invokeTestRunnable$10(KtUsefulTestCase.java:406)
	at com.intellij.testFramework.EdtTestUtilKt.runInEdtAndWait(EdtTestUtil.kt:63)
	at org.jetbrains.kotlin.test.testFramework.KtUsefulTestCase.invokeTestRunnable(KtUsefulTestCase.java:405)
	at org.jetbrains.kotlin.test.testFramework.KtUsefulTestCase.runTest(KtUsefulTestCase.java:392)
	at org.jetbrains.kotlin.test.testFramework.KtUsefulTestCase.defaultRunBare(KtUsefulTestCase.java:423)
	at com.intellij.testFramework.EdtTestUtil$Companion$runInEdtAndWait$1.invoke(EdtTestUtil.kt:18)
	at com.intellij.testFramework.EdtTestUtil$Companion$runInEdtAndWait$1.invoke(EdtTestUtil.kt:13)
	at com.intellij.testFramework.EdtTestUtilKt$runInEdtAndWait$3.run(EdtTestUtil.kt:67)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:303)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:419)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
`

**Comment by AlexBeggs** [comment]
@neetopia
