### ISSUE TITLE
Missing extension point: org.jetbrains.kotlin.com.intellij.psi.treeChangeListener

### ISSUE THREAD

**Issue by tschuchortdev** [google/ksp#576]
I have been running into the following error when trying to update KSP in my project kotlin-compile-testing:

```
java.lang.IllegalArgumentException: Missing extension point: org.jetbrains.kotlin.com.intellij.psi.treeChangeListener in container org.jetbrains.kotlin.com.intellij.mock.MockProject@68e2f3db
	at org.jetbrains.kotlin.com.intellij.openapi.extensions.impl.ExtensionsAreaImpl.getExtensionPoint(ExtensionsAreaImpl.java:260)
	at org.jetbrains.kotlin.com.intellij.openapi.extensions.BaseExtensionPointName.getPointImpl(BaseExtensionPointName.java:28)
	at org.jetbrains.kotlin.com.intellij.openapi.extensions.ProjectExtensionPointName.getExtensions(ProjectExtensionPointName.java:37)
	at org.jetbrains.kotlin.com.intellij.psi.impl.PsiManagerImpl.fireEvent(PsiManagerImpl.java:350)
	at org.jetbrains.kotlin.com.intellij.psi.impl.PsiManagerImpl.beforePropertyChange(PsiManagerImpl.java:249)
	at org.jetbrains.kotlin.com.intellij.psi.impl.file.impl.FileManagerImpl.firePropertyChangedForUnloadedPsi(FileManagerImpl.java:148)
	at org.jetbrains.kotlin.com.intellij.openapi.application.WriteAction.run(WriteAction.java:102)
	at org.jetbrains.kotlin.com.intellij.psi.impl.PsiManagerImpl.dropPsiCaches(PsiManagerImpl.java:87)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.doAnalysis(KotlinSymbolProcessingExtension.kt:111)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:120)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:86)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:540)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:531)
	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:113)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:531)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.repeatAnalysisIfNeeded(KotlinToJVMBytecodeCompiler.kt:501)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:188)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:154)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:169)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:52)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:90)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:44)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:98)
	at com.tschuchort.compiletesting.AbstractKotlinCompilation.compileKotlin(AbstractKotlinCompilation.kt:184)
	at com.tschuchort.compiletesting.KotlinCompilation.compileJvmKotlin(KotlinCompilation.kt:469)
	at com.tschuchort.compiletesting.KotlinCompilation.compile(KotlinCompilation.kt:645)
```

The failing test case contains the following symbol processor:
```
object : AbstractTestSymbolProcessor(env.codeGenerator) {
                    override fun process(resolver: Resolver): List<KSAnnotated> {
                        val symbols = resolver.getSymbolsWithAnnotation("foo.bar.TestAnnotation").toList()
                        if (symbols.isNotEmpty())  {
                            assertThat(symbols.size).isEqualTo(1)
                            val klass = symbols.first()
                            check(klass is KSClassDeclaration)
                            val qName = klass.qualifiedName ?: error("should've found qualified name")
                            val genPackage = "${qName.getQualifier()}.generated"
                            val genClassName = "${qName.getShortName()}_Gen"
                            codeGenerator.createNewFile(
                                dependencies = Dependencies.ALL_FILES,
                                packageName = genPackage,
                                fileName = genClassName
                            ).bufferedWriter(Charsets.UTF_8).use {
                                it.write("""
                            package $genPackage
                            class $genClassName() {}
                        """.trimIndent())
                            }
                        }
                        return emptyList()
                    }
                }
```

I have narrowed the issue down to the `codeGenerator.createNewFile` call but don't really know how to proceed further. Does anyone have an idea what the issue could be?

The last version I can confirm to work with this code is 1.5.10-1.0.0-beta02.

**Comment by ting-yuan** [comment]
Can you try to register a dummy treeChangeListener like this in ComponentRegistrar?

https://github.com/google/ksp/blob/4b968db9ff03437037695cc453deb96348543158/compiler-plugin/src/main/kotlin/com/google/devtools/ksp/KotlinSymbolProcessingPlugin.kt#L94

**Comment by tschuchortdev** [comment]
That seems to do the trick. All tests pass now. Thanks for the help!
