### ISSUE TITLE
Android project configuration exception:java.lang.NoClassDefFoundError: com/android/build/api/dsl/AndroidSourceSet 

### ISSUE THREAD

**Issue by caoyulubao666** [google/ksp#589]
Use groovy script to configuration Android project, but an exception was thrown. what should i do?

java.lang.NoClassDefFoundError: com/android/build/api/dsl/AndroidSourceSet
	at com.google.devtools.ksp.gradle.AndroidPluginIntegration$decorateAndroidExtension$1$1.invoke(AndroidPluginIntegration.kt:73)
	at com.google.devtools.ksp.gradle.KspGradleSubplugin.createKspConfigurations$lambda-4(KspSubplugin.kt:183)
	at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction$1$1.run(DefaultCollectionCallbackActionDecorator.java:100)
	at org.gradle.configuration.internal.DefaultUserCodeApplicationContext.reapply(DefaultUserCodeApplicationContext.java:60)
	at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction$1.run(DefaultCollectionCallbackActionDecorator.java:97)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
	at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction.execute(DefaultCollectionCallbackActionDecorator.java:94)
	at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:163)
	at com.google.devtools.ksp.gradle.KspGradleSubplugin.createKspConfigurations$gradle_plugin(KspSubplugin.kt:182)
	at com.google.devtools.ksp.gradle.AndroidPluginIntegration.decorateAndroidExtension(AndroidPluginIntegration.kt:73)
	at com.google.devtools.ksp.gradle.AndroidPluginIntegration.applyIfAndroidProject$lambda-1$lambda-0(AndroidPluginIntegration.kt:49)
	at org.gradle.api.internal.plugins.DefaultPluginManager$3.execute(DefaultPluginManager.java:252)
	at org.gradle.api.internal.plugins.DefaultPluginManager$3.execute(DefaultPluginManager.java:249)

**Comment by ting-yuan** [comment]
Would you mind to update Gradle to 6.1.1 / Android Gradle Plugin 4.0.0 or higher? KSP depends on AGP 4.0.0+, which in turn depends on Gradle 6.1.1+.

**Comment by caoyulubao666** [comment]
Thanks for you replay. But my project use Gradle 6.3 / AGP 4.0.0

**Comment by ting-yuan** [comment]
I see. Looks like the [change](https://cs.android.com/android-studio/platform/tools/base/+/e54bd835f3b81a7eacdac05a79467c375662f74b:build-system/gradle-api/src/main/java/com/android/build/api/dsl/AndroidSourceSet.kt;dlc=9312a29cf6fcdb53f9728445ac2966cfde323409) in the not found interface was introduced in a later release.

Can you try to update to Gradle 6.5 / AGP 4.1.0?

**Comment by caoyulubao666** [comment]
Thanks, The problem has been solved.

**Comment by haizerdev** [comment]
With APG 7.0.3 reproduced!
