### ISSUE TITLE
NPE with nested annotation in Java

### ISSUE THREAD

**Issue by amandeepg** [google/ksp#622]
When the code that's processed is:
```java
@Builder
@MyAnnotationWithClass(MyAnnotation.Inner.class)
@interface MyAnnotation {
    @interface Inner {
    }
}

@interface MyAnnotationWithClass {
}
```

Processed with:
```kotlin
resolver
    .getSymbolsWithAnnotation(Builder::class.qualifiedName!!)
    .filterIsInstance<KSClassDeclaration>()
    .first()
    .annotations
    .map { it.arguments }
    .forEach { logger.info(it.toString()) }
```

Throws:
```
Caused by: java.lang.NullPointerException
	at com.google.devtools.ksp.symbol.impl.java.KSClassDeclarationJavaImpl.asStarProjectedType(KSClassDeclarationJavaImpl.kt:149)
	at com.google.devtools.ksp.symbol.impl.java.KSAnnotationJavaImpl.calcValue(KSAnnotationJavaImpl.kt:122)
	at com.google.devtools.ksp.symbol.impl.java.KSAnnotationJavaImpl.access$calcValue(KSAnnotationJavaImpl.kt:33)
	at com.google.devtools.ksp.symbol.impl.java.KSAnnotationJavaImpl$arguments$2.invoke(KSAnnotationJavaImpl.kt:92)
	at com.google.devtools.ksp.symbol.impl.java.KSAnnotationJavaImpl$arguments$2.invoke(KSAnnotationJavaImpl.kt:77)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.google.devtools.ksp.symbol.impl.java.KSAnnotationJavaImpl.getArguments(KSAnnotationJavaImpl.kt:77)
```

Sample gradle project attached: [Archive.zip](https://github.com/google/ksp/files/7147517/Archive.zip)

**Comment by neetopia** [comment]
Actually this is a non-issue, your java class is declared in a file with a different name from the class name, which will cause kotlin compiler unable to locate the class, fixing the file name resolves this issue.

**Comment by elihart** [comment]
Are you sure? In my repro case the outer class name matches the file name, and the outer class can be processed without error. It only starts failing when I add an inner class with an annotation. 

See this unit test - which reproduces the issue when the compilation mode input is changed to KSP
https://github.com/airbnb/epoxy/blob/687c8451e3f1afc472ab35f69599e68ae8f66791/epoxy-processortest/src/test/java/com/airbnb/epoxy/ModelProcessorTest.kt#L93

If the file name is the issue, could the error message be improved to be more helpful?

**Comment by amandeepg** [comment]
@elihart Fixing the filename works in my sample project, but in my unit tests it still fails. I'm also using https://github.com/tschuchortdev/kotlin-compile-testing like you are. Perhaps the issue is with that library?

**Comment by elihart** [comment]
yes, it seems to be an issue with that testing library :/
