### ISSUE TITLE
KSTypeReference.resolve()?.declaration thows IllegalStateException when referencing a type alias in another module

### ISSUE THREAD

**Issue by evant** [google/ksp#68]
If you have a typealias in module A:

```kotlin
typealias Foo = List<String>
```

and a method returning that type in module B depending on A:
```kotlin
fun foo(): Foo = ...
```

then do `method.type?.resolve()?.declaration`, you get an IllegalStateException.

```
e: java.lang.IllegalStateException
        at org.jetbrains.kotlin.ksp.processing.impl.ResolverImpl.findDeclaration(ResolverImpl.kt:351)
        at org.jetbrains.kotlin.ksp.symbol.impl.kotlin.KSTypeImpl$declaration$2.invoke(KSTypeImpl.kt:34)
        at org.jetbrains.kotlin.ksp.symbol.impl.kotlin.KSTypeImpl$declaration$2.invoke(KSTypeImpl.kt:18)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at org.jetbrains.kotlin.ksp.symbol.impl.kotlin.KSTypeImpl.getDeclaration(KSTypeImpl.kt)
```

**Comment by ting-yuan** [comment]
Fixed in #182. Tested in #188.
