### ISSUE TITLE
Kotlin Metadata not properly generated

### ISSUE THREAD

**Issue by glureau** [google/ksp#731]
Context: KMP multi-module project, using `kspMetadata` to generate code based on an annotation, KSP (snapshot close to 1.6.0-1.0.1 + typealias support)

Given the code:
```
interface MyClass<T> {
    val size: Int
}

@KustomExport
typealias MyClassDouble = MyClass<Double>
```

My processor generates some files, and then an exception occurred.

<details>
  <summary>Generated file</summary>

```
import kotlin.Double
import kotlin.Int
import kotlin.js.JsExport
import com.deezer.kmp.api.MyClass as CommonMyClass

@JsExport
public external interface MyClass {
    public val size: Int
}

private class ImportedMyClass(
    internal val exported: MyClass
) : CommonMyClass<Double> {
    public override val size: Int
        get() = exported.size
}

private class ExportedMyClass(
    internal val common: CommonMyClass<Double>
) : MyClass {
    public override val size: Int
        get() = common.size
}

public fun CommonMyClass<Double>.exportMyClass(): MyClass = (this as? ImportedMyClass)?.exported ?:
        ExportedMyClass(this)

public fun MyClass.importMyClass(): CommonMyClass<Double> = (this as? ExportedMyClass)?.common ?:
        ImportedMyClass(this)
```
</details>

<details open>
  <summary>Exception stacktrace</summary>

```
e: java.lang.IllegalStateException: No descriptor found for class com.deezer.kmp.api.MyClass
        at org.jetbrains.kotlin.cli.metadata.MetadataSerializer$performSerialization$1.visitClassOrObject(MetadataSerializer.kt:92)
        at org.jetbrains.kotlin.psi.KtVisitorVoid.visitClassOrObject(KtVisitorVoid.java:469)
        at org.jetbrains.kotlin.psi.KtVisitorVoid.visitClassOrObject(KtVisitorVoid.java:21)
        at org.jetbrains.kotlin.psi.KtVisitor.visitClass(KtVisitor.java:33)
        at org.jetbrains.kotlin.psi.KtVisitorVoid.visitClass(KtVisitorVoid.java:33)
        at org.jetbrains.kotlin.psi.KtVisitorVoid.visitClass(KtVisitorVoid.java:463)
        at org.jetbrains.kotlin.psi.KtVisitorVoid.visitClass(KtVisitorVoid.java:21)
        at org.jetbrains.kotlin.psi.KtClass.accept(KtClass.kt:20)
        at org.jetbrains.kotlin.psi.KtElementImplStub.accept(KtElementImplStub.java:49)
        at org.jetbrains.kotlin.cli.metadata.MetadataSerializer.performSerialization(MetadataSerializer.kt:68)
        at org.jetbrains.kotlin.cli.metadata.MetadataSerializer.serialize(MetadataSerializer.kt:55)
        at org.jetbrains.kotlin.cli.metadata.K2MetadataCompiler.doExecute(K2MetadataCompiler.kt:117)
        at org.jetbrains.kotlin.cli.metadata.K2MetadataCompiler.doExecute(K2MetadataCompiler.kt:40)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:92)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:44)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:98)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1618)
        at sun.reflect.GeneratedMethodAccessor110.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357)
        at sun.rmi.transport.Transport$1.run(Transport.java:200)
        at sun.rmi.transport.Transport$1.run(Transport.java:197)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
        at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

```
</details>

The targeted class in the stacktrace points to the original interface, not the generated one. If I remove the annotation, no more generated file and the build can finish without the issue.

**Comment by glureau** [comment]
I'm also having the same issue by using @file:MyAnnotation when trying to generate a class.
It's breaking in the first class of the module and not the generated class. Also I cannot reproduce this on an interface generation. And eventually it doesn't matter if I write the class or just create a newFile without writing any code in it, so I presume it's coming from the usage of KSP itself... I'll try to make a simple reproducer when I got some time.

**Comment by glureau** [comment]
Old issue, I don't think it's still relevant today (will re-open if needed).
