### ISSUE TITLE
Migrating from kapt to ksp gives error

### ISSUE THREAD

**Issue by apkelly** [google/ksp#755]
I have a working Kapt processor, and I've move it over to KSP, its very basic, it just parses an json file and generates classes using KotlinPoet. 

I'm using kotlin 1.5.31, ksp 1.5.31-1.0.0, and kotlinpoet 1.10.2

However, when running the ksp task never finished. I get the following error

> Task :xxx-client:kspMyBuildFlavorReleaseKotlin FAILED
> e: java.lang.StackOverflowError
>         at java.base/java.lang.ClassLoader.defineClass1(Native Method)
>         at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
>         at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
>         at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
>         at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
>         at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
>         at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
>         at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
>         at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
>         at org.jetbrains.kotlin.storage.LockBasedStorageManager$MapBasedMemoizedFunction.invoke(LockBasedStorageManager.java:593)
>         at org.jetbrains.kotlin.storage.LockBasedStorageManager$MapBasedMemoizedFunctionToNotNull.invoke(LockBasedStorageManager.java:651)
>         at org.jetbrains.kotlin.resolve.lazy.descriptors.AbstractLazyMemberScope.getContributedVariables(AbstractLazyMemberScope.kt:139)
>         at org.jetbrains.kotlin.resolve.lazy.descriptors.LazyClassMemberScope.getContributedVariables(LazyClassMemberScope.kt:380)
>         at org.jetbrains.kotlin.resolve.lazy.LazyDeclarationResolver$resolveToDescriptor$1.visitProperty(LazyDeclarationResolver.kt:182)
>         at org.jetbrains.kotlin.resolve.lazy.LazyDeclarationResolver$resolveToDescriptor$1.visitProperty(LazyDeclarationResolver.kt:94)
>         at org.jetbrains.kotlin.psi.KtProperty.accept(KtProperty.java:58)
>         at org.jetbrains.kotlin.resolve.lazy.LazyDeclarationResolver.resolveToDescriptor(LazyDeclarationResolver.kt:94)
>         at org.jetbrains.kotlin.resolve.lazy.LazyDeclarationResolver.resolveToDescriptor(LazyDeclarationResolver.kt:91)
>         at org.jetbrains.kotlin.resolve.lazy.ResolveSession.resolveToDescriptor(ResolveSession.java:368)
>         at com.google.devtools.ksp.processing.impl.ResolverImpl.resolveDeclaration(ResolverImpl.kt:440)
>         at com.google.devtools.ksp.symbol.impl.kotlin.KSPropertyDeclarationImpl$propertyDescriptor$2.invoke(KSPropertyDeclarationImpl.kt:43)
>         at com.google.devtools.ksp.symbol.impl.kotlin.KSPropertyDeclarationImpl$propertyDescriptor$2.invoke(KSPropertyDeclarationImpl.kt:42)
>         at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
>         at com.google.devtools.ksp.symbol.impl.kotlin.KSPropertyDeclarationImpl.getPropertyDescriptor(KSPropertyDeclarationImpl.kt:42)
>         at com.google.devtools.ksp.symbol.impl.kotlin.KSPropertyDeclarationImpl.access$getPropertyDescriptor(KSPropertyDeclarationImpl.kt:34)
>         at com.google.devtools.ksp.symbol.impl.kotlin.KSPropertyDeclarationImpl$getter$2.invoke(KSPropertyDeclarationImpl.kt:68)
>         at com.google.devtools.ksp.symbol.impl.kotlin.KSPropertyDeclarationImpl$getter$2.invoke(KSPropertyDeclarationImpl.kt:65)
>         at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
>         at com.google.devtools.ksp.symbol.impl.kotlin.KSPropertyDeclarationImpl.getGetter(KSPropertyDeclarationImpl.kt:65)
>         at com.google.devtools.ksp.processing.impl.ResolverImpl$collectAnnotatedSymbols$visitor$1.visitPropertyDeclaration(ResolverImpl.kt:325)
>         at com.google.devtools.ksp.processing.impl.ResolverImpl$collectAnnotatedSymbols$visitor$1.visitPropertyDeclaration(ResolverImpl.kt:288)
>         at com.google.devtools.ksp.symbol.impl.kotlin.KSPropertyDeclarationImpl.accept(KSPropertyDeclarationImpl.kt:103)
>         at com.google.devtools.ksp.processing.impl.ResolverImpl$collectAnnotatedSymbols$visitor$1.visitClassDeclaration(ResolverImpl.kt:302)
>         at com.google.devtools.ksp.processing.impl.ResolverImpl$collectAnnotatedSymbols$visitor$1.visitClassDeclaration(ResolverImpl.kt:288)
>         at com.google.devtools.ksp.symbol.impl.kotlin.KSClassDeclarationImpl.accept(KSClassDeclarationImpl.kt:119)
>         at com.google.devtools.ksp.processing.impl.ResolverImpl$collectAnnotatedSymbols$visitor$1.visitFile(ResolverImpl.kt:296)
>         at com.google.devtools.ksp.processing.impl.ResolverImpl$collectAnnotatedSymbols$visitor$1.visitFile(ResolverImpl.kt:288)
>         at com.google.devtools.ksp.symbol.impl.kotlin.KSFileImpl.accept(KSFileImpl.kt:61)
>         at com.google.devtools.ksp.processing.impl.ResolverImpl.collectAnnotatedSymbols(ResolverImpl.kt:343)
>         at com.google.devtools.ksp.processing.impl.ResolverImpl.access$collectAnnotatedSymbols(ResolverImpl.kt:104)
>         at com.google.devtools.ksp.processing.impl.ResolverImpl$newAnnotatedSymbols$2.invoke(ResolverImpl.kt:354)
>         at com.google.devtools.ksp.processing.impl.ResolverImpl$newAnnotatedSymbols$2.invoke(ResolverImpl.kt:353)
>         at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
>         at com.google.devtools.ksp.processing.impl.ResolverImpl.getNewAnnotatedSymbols(ResolverImpl.kt:353)
>         at com.google.devtools.ksp.processing.impl.ResolverImpl.getSymbolsWithAnnotation(ResolverImpl.kt:280)
>         at com.google.devtools.ksp.processing.Resolver$DefaultImpls.getSymbolsWithAnnotation$default(Resolver.kt:47)
>         at dev.zacsweers.moshix.ksp.JsonClassSymbolProcessor.process(JsonClassSymbolProcessorProvider.kt:112)
>         at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$4$1.invoke(KotlinSymbolProcessingExtension.kt:186)
>         at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$4$1.invoke(KotlinSymbolProcessingExtension.kt:184)
>         at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.handleException(KotlinSymbolProcessingExtension.kt:278)
>         at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.doAnalysis(KotlinSymbolProcessingExtension.kt:184)
>         at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:120)
>         at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:86)
>         at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:252)
>         at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:243)
>         at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:113)
>         at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:243)
>         at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.repeatAnalysisIfNeeded(KotlinToJVMBytecodeCompiler.kt:213)
>         at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.repeatAnalysisIfNeeded(KotlinToJVMBytecodeCompiler.kt:213)
>         at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.repeatAnalysisIfNeeded(KotlinToJVMBytecodeCompiler.kt:213)
>         at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.repeatAnalysisIfNeeded(KotlinToJVMBytecodeCompiler.kt:213)

>

**Comment by ting-yuan** [comment]
Looks like it is stuck in multiple round loops, which is implemented recursively. Can you see whether some outputs are written repeatedly? The multiple round loop won't [stop](https://github.com/google/ksp/blob/main/docs/multi-round.md#termination-condition) if there are files written.

btw, a check in KSP is introduced to prevent an output from being written repeatedly in 1.0.1.

**Comment by apkelly** [comment]
My output files are generated as expected, not sure how to check if they're being repeatedly written too....the timestamps don't seem to be changing. I'll try 1.0.1 and see if that fixes things.

**Comment by apkelly** [comment]
My SymbolProcessor is pretty straight forward.

```
    override fun process(resolver: Resolver): List<KSAnnotated> {
        this.resolver = resolver
        generateClasses()

        return emptyList()
    }
```

The generateClasses() method just reads my json and creates some classes using KotlinPoet, so it never needs to defer processing until a later round.

**Comment by apkelly** [comment]
Wrapping the `createNewFile` method in a try/catch, means my processors completes successfully.

```
        try {
            codeGenerator.createNewFile(
                dependencies = Dependencies(false, *resolver.getAllFiles().toList().toTypedArray()),
                packageName = EVENTS_PACKAGE_NAME,
                fileName = fileName
            ).use { outputStream ->
                outputStream.writer()
                    .use {
                        fileSpec.writeTo(it)
                    }
            }
        } catch (faee: FileAlreadyExistsException) {
            // do nothing.
        }
```

**Comment by ting-yuan** [comment]
Yep, the FileAlreadyExistsException indicates that the processor tried to rewrite some output which is generated in previous round.

**Comment by apkelly** [comment]
So catching and ignoring is a valid pattern in this scenario? Or is there a fix likely to come in future that would prevent multiple rounds from executing?

**Comment by ting-yuan** [comment]
Multi-round processing is designed for cooperation among processors. A typical use case is that a processor generates a file in round N and another processor picks it up in round N + 1. When there's no new outputs, processors run to a fixed point and the entire processing terminates. KSP chose this somewhat implicit termination condition instead of having processors report an explicit flag, because it is a common approach in the communities when the API is designed.

In contrast to catching and ignoring the exception, you could also write the file once in [SymbolProcessor.finish()](https://github.com/google/ksp/blob/main/api/src/main/kotlin/com/google/devtools/ksp/processing/SymbolProcessor.kt#L43) if the generated files are not expected to be consumed by other processors.

**Comment by apkelly** [comment]
Cool, I'll take a look. 

I am trying to work out how moshi-ksp works in this scenario though. They seem to be doing the same thing as me, find an annotation and then generate class files, they don't seem to have the same error, and don't handle the FileAlreadyExistsException, and aren't using SymbolProcessor.finish() as far as I can tell.

https://github.com/ZacSweers/MoshiX/blob/main/moshi-ksp/moshi-ksp/src/main/kotlin/dev/zacsweers/moshix/ksp/JsonClassSymbolProcessorProvider.kt

**Comment by apkelly** [comment]
Running our code generation in `SymbolProcessor.finish()` fixed the issue with FileAlreadyExistsException!

Thanks for your help!

**Comment by liujingxing** [comment]
I have the same problem, this is my code in [RxHttp](https://github.com/liujingxing/rxhttp/blob/master/rxhttp-compiler/src/main/java/com/rxhttp/compiler/KspProcessor.kt), but I don't think it's elegant enough

```kotlin
class KspProcessor(private val env: SymbolProcessorEnvironment) : SymbolProcessor {

    private var processed: Boolean = false

    override fun process(resolver: Resolver): List<KSAnnotated> {
        if (processed) return emptyList()
        // generates classes
        processed = true
        return emptyList()
    }

    override fun finish() {}

    override fun onError() {}
}
```

**Comment by mistletoe5215** [comment]
> 

i write the file once in SymbolProcessor.finish() ,but the build panel show the following warning info https://github.com/google/ksp/issues/786,hope to fix it

**Comment by mistletoe5215** [comment]
@ting-yuan 
> i write the file once in SymbolProcessor.finish() ,but the build panel show the following warning info #786 to fix it

**Comment by hfmehmed** [comment]
Closing this as the reported issue seems fixed.
