### ISSUE TITLE
Unknown error in kotlin compiler

### ISSUE THREAD

**Issue by popovanton0** [google/ksp#797]
When using custom ksp-based annotation processor, I encountered this exception:
```
 > Task :my-module:kspDebugKotlin FAILED
 e: java.lang.IllegalStateException: Should not be called!
     at org.jetbrains.kotlin.types.ErrorUtils$1.getPackage(ErrorUtils.java:94)
     at org.jetbrains.kotlin.descriptors.DescriptorUtilKt.resolveClassByFqName(descriptorUtil.kt:24)
     at org.jetbrains.kotlin.resolve.checkers.ExperimentalUsageChecker$Companion.checkCompilerArguments$checkAnnotation(ExperimentalUsageChecker.kt:340)
     at org.jetbrains.kotlin.resolve.checkers.ExperimentalUsageChecker$Companion.checkCompilerArguments(ExperimentalUsageChecker.kt:363)
     at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:114)
     at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:253)
     at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.repeatAnalysisIfNeeded(KotlinToJVMBytecodeCompiler.kt:223)
     at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:100)
     at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:58)
     at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:170)
     at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:52)
     at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:92)
     at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:44)
     at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:98)
     at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1618)
     ...
```

It occurred after I updated ksp from `1.5.21-beta07` to `1.6.0-1.0.2`. I don't even know how to approach debugging this issue.

**Comment by RinOrz** [comment]
I have the same problem. The error report is related to calling `CodeGenerator.createNewFile` method. When I comment out this call, compiler will not report an error.

**Comment by ting-yuan** [comment]
This is a bug that happened when KSP is reporting another exception or error. The error message / exception that KSP tried to report might have been printed in the log prior to this exception. Could you check if there was another error message or exception in the log?

By the way, I would really appreciate if you could provide a reproduce case.

**Comment by RinOrz** [comment]
Just report `java.lang.IllegalStateException: Should not be called!`, In addition, this problem can be solved temporarily through the call to **try catch** `CodeGenerator.createNewFile`

It's a little difficult to reproduce the case because my project is a little big... But I'll try to create a minimum reproduction case sometime

**Comment by RinOrz** [comment]
@ting-yuan I can't reproduce a minimum project, so I uploaded the project that encountered the bug.

#### Reproduction:
https://github.com/RinOrz/ksp-issue797/

#### KSP Part:
https://github.com/RinOrz/ksp-issue797/blob/master/compiler-base/ksp/src/main/kotlin/MetaPluginProcessorProvider.kt
##### Possible error part:
https://github.com/RinOrz/ksp-issue797/blob/master/compiler-base/ksp/src/main/kotlin/DiagnosticProcessor.kt#L50-L87

#### Exception:
https://github.com/RinOrz/ksp-issue797/runs/5083336430?check_suite_focus=true#step:4:289

**Comment by RinOrz** [comment]
Further, I found that this error is related to `Dependencies`, when I set 'Dependencies.aggregating' to `false`, everything will works, but on the contrary, even use `Dependencies.ALL_FILES`, this unknown error will still be thrown.

**Comment by ting-yuan** [comment]
@RinOrz Thanks a lot for the repro case! A fix (to the error log) is on the way.

btw, the real error message hidden by this bug is:
```
kotlin.io.FileAlreadyExistsException: /path/to/catnip/compiler/build/generated/ksp/main/kotlin/com/meowool/meta/catnip/DiagnosticsMessagesExtension.kt
	at com.google.devtools.ksp.processing.impl.CodeGeneratorImpl.createNewFile(CodeGeneratorImpl.kt:74)
	at com.google.devtools.ksp.processing.CodeGenerator$DefaultImpls.createNewFile$default(CodeGenerator.kt:59)
	at com.meowool.meta.UtilsKt.createKotlinFile(Utils.kt:56)
	at com.meowool.meta.DiagnosticProcessor.process(DiagnosticProcessor.kt:50)
	at com.meowool.meta.MetaPluginProcessorProvider$create$1.process(MetaPluginProcessorProvider.kt:40)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$4$1.invoke(KotlinSymbolProcessingExtension.kt:195)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$4$1.invoke(KotlinSymbolProcessingExtension.kt:193)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.handleException(KotlinSymbolProcessingExtension.kt:287)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.doAnalysis(KotlinSymbolProcessingExtension.kt:193)
```

**Comment by RinOrz** [comment]
> Looks like that `DiagnosticsMessagesExtension.kt` is written twice in different rounds.

But I don't seem to have enabled multi round processing, or is there a way to solve it?

**Comment by ting-yuan** [comment]
Multiple round processing is part of the processing lifecycle design and is always on. Processors are repeatedly called [until there is no new file generated](https://github.com/google/ksp/blob/main/docs/multi-round.md#termination-condition). If only one round is desired, you may use a flag to skip processing like [this](https://github.com/google/ksp/blob/main/examples/playground/test-processor/src/main/kotlin/TestProcessor.kt#L20).

**Comment by RinOrz** [comment]
@ting-yuan Thank you, that is, I only need to solve the problem of multiple rounds of processing to resolved this error, even if I don't have to wait until the new KSP patch released?

**Comment by ting-yuan** [comment]
Yes, that should make the error message away. BTW, 1.6.10-1.0.3 which contains the fix is also released :)

**Comment by mehdiyari** [comment]
Hey @ting-yuan, I noticed this issue and managed to fix it by checking if the processor had already generated all files. If the file exists, I skip the second round of processing.

However, this solution doesn't seem to follow best practices. Are there any plans to address this issue from the Code Generator side?

**Comment by BorislavKamenov** [comment]
You can ignore the second round by putting boolean flag and marking is as true so it will pass down the code only once. Example:

```
class MyAnnotationsProcessor(val codeGenerator: CodeGenerator, val logger: KSPLogger) : SymbolProcessor {
    var invoked = false

    override fun process(resolver: Resolver): List<KSAnnotated> {

        if (invoked) {
            return emptyList()
        }
        invoked = true
        
        // val file = codeGenerator.createNewFile(...)
    }
}
```
