### ISSUE TITLE
KSP Common Metadata Task Fails with null for default annotation arguments

### ISSUE THREAD

**Issue by agrosner** [google/ksp#885]
KSP Version: 1.6.10-1.0.4

I have a [class](https://github.com/agrosner/DBFlow/blob/fec0f91acfe75d03244df4a5cf5226557e0a71f0/tests/src/commonMain/kotlin/com/dbflow5/test/SimpleModel.kt#L7) defined in commonMain for a testing module:
```kotlin 
@Table
data class SimpleModel(@PrimaryKey val id: String)
```

The place it fails is [here](https://github.com/agrosner/DBFlow/blob/fec0f91acfe75d03244df4a5cf5226557e0a71f0/ksp/src/main/java/com/dbflow5/ksp/parser/KSPropertyDeclarationParser.kt#L48)

where I am taking the `KSValueArgument` and inferring return type into a data model in order to grab its value. When I run the processor on a specific target like jvm or android, it finds the proper default values. But running the common metadata task: 
```
 Task :tests:kspKotlinMetadata FAILED
e: [ksp] java.lang.NullPointerException: null cannot be cast to non-null type kotlin.Boolean
	at com.dbflow5.ksp.parser.KSPropertyDeclarationParser.parse(KSPropertyDeclarationParser.kt:135)
```
All arguments are `null` from the corresponding [annotation](https://github.com/agrosner/DBFlow/blob/fec0f91acfe75d03244df4a5cf5226557e0a71f0/core/src/commonMain/kotlin/com/dbflow5/annotation/PrimaryKey.kt#L8)

like:
```kotlin
annotation class PrimaryKey(
    /**
     * Specifies if the column is autoincrementing or not
     */
    val autoincrement: Boolean = false, // this should not be null if missing...

```

The fix is to ignore default values when `null` and _also_ supply defaults in the processor, but that would introduce unnecessary duplication to keep the arguments up with their default values...

**Comment by neetopia** [comment]
This is still pending upstream fix, likely won't make it in 1.7.0 release.

**Comment by Lukellmann** [comment]
Any updates on this?

**Comment by neetopia** [comment]
No, it is not prioritized at the moment

**Comment by Lukellmann** [comment]
Can I somehow help with this? Is it a problem with KSP or the Kotlin compiler?

**Comment by Lukellmann** [comment]
Is there already an issue in the Kotlin YouTrack?

**Comment by neetopia** [comment]
Not sure, I will file one if it is not yet created.

**Comment by lukellmann** [comment]
> Not sure, I will file one if it is not yet created.

Could you provide the issue link so I can follow along there? I wasn't able to find it.

**Comment by neetopia** [comment]
Thanks for the reminder, created one in YouTrack: https://youtrack.jetbrains.com/issue/KT-59566/Annotation-default-value-is-not-populated-in-metadata-for-libraries

**Comment by eygraber** [comment]
I started seeing something similar after updating to KSP2:

```
java.lang.NullPointerException: null cannot be cast to non-null type org.jetbrains.kotlin.load.java.structure.impl.JavaClassImpl
        at com.google.devtools.ksp.impl.symbol.kotlin.UtilKt.getDefaultValue(util.kt:419)
        at com.google.devtools.ksp.impl.symbol.kotlin.KSAnnotationImpl$defaultArguments$2.invoke(KSAnnotationImpl.kt:77)
        at com.google.devtools.ksp.impl.symbol.kotlin.KSAnnotationImpl$defaultArguments$2.invoke(KSAnnotationImpl.kt:60)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.google.devtools.ksp.impl.symbol.kotlin.KSAnnotationImpl.getDefaultArguments(KSAnnotationImpl.kt:60)
        at com.google.devtools.ksp.impl.symbol.kotlin.KSAnnotationImpl$arguments$2.invoke(KSAnnotationImpl.kt:54)
        at com.google.devtools.ksp.impl.symbol.kotlin.KSAnnotationImpl$arguments$2.invoke(KSAnnotationImpl.kt:51)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.google.devtools.ksp.impl.symbol.kotlin.KSAnnotationImpl.getArguments(KSAnnotationImpl.kt:51)
        at com.google.devtools.ksp.impl.symbol.kotlin.KSPropertyDeclarationImpl$annotations$2$4.invoke(KSPropertyDeclarationImpl.kt:65)
        at com.google.devtools.ksp.impl.symbol.kotlin.KSPropertyDeclarationImpl$annotations$2$4.invoke(KSPropertyDeclarationImpl.kt:61)
        at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:171)
        at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
        at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:331)
        at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:318)
        at com.google.devtools.ksp.visitor.KSValidateVisitor.visitAnnotated(KSValidateVisitor.kt:126)
        at com.google.devtools.ksp.visitor.KSValidateVisitor.visitDeclaration(KSValidateVisitor.kt:23)
```

Is this the same issue, and would https://youtrack.jetbrains.com/issue/KT-59526/Store-annotation-default-values-in-metadata-on-JVM fix it?

**Comment by BoD** [comment]
@eygraber It doesn't seem clear if this is the same issue so I just opened #2112

**Comment by eygraber** [comment]
@BoD thanks for filing that. I guess my issue was the same as yours because it is fixed in 1.0.26+
