### ISSUE TITLE
KSP cannot find KClass provided via annotation

### ISSUE THREAD

**Issue by brizzbuzz** [google/ksp#888]
Hey 👋 I have a feeling that this might just be me missing something obvious, but it seems like KSP cannot perform reflection on a KClass provided via an annotation. 

Say for example I have some code 

```kotlin
@IWantToFindThis
interface SomethingAmazing {
  // ..
}


interface AnotherAmazingThing {
  @TriggerKSP(clazz = SomethingAmazing::class)
  val coolProp: Thingy 
}
```

If I were to write a processor here

```kotlin
// ..
val triggerAnnotation = prop.getAnnotationsByType(TriggerKSP::class).first()
val failsHere = triggerAnnotation.clazz.findAnnotation<IWantToFindThis>()
```

KSP seems to not be able to find `SomethingAmazing`

```
> Task :lerasium-playground:kspKotlin FAILED
e: [ksp] com.google.devtools.ksp.KSTypeNotPresentException: java.lang.ClassNotFoundException: io.bkbn.lerasium.playground.SomethingAmazing
        at com.google.devtools.ksp.UtilsKt.asClass(utils.kt:505)
        at com.google.devtools.ksp.UtilsKt.createInvocationHandler$lambda-8(utils.kt:381)
        at jdk.proxy19/jdk.proxy19.$Proxy151.clazz(Unknown Source)
        // ..
Caused by: java.lang.ClassNotFoundException: io.bkbn.lerasium.playground.SomethingAmazing
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:375)
        at com.google.devtools.ksp.UtilsKt.asClass(utils.kt:503)
        // ..
```

**Comment by unredundant** [comment]
I was able to hack my way around this with the following, but would be nice if this was accessible in a more streamlined manner 

```kotlin 
(prop.annotations.toList().first().arguments.first().value as KSType)
      .declaration.getAnnotationsByType(IWantToFindThis::class).first()
```

**Comment by ting-yuan** [comment]
Can you provide a sample project to reproduce this issue?

**Comment by Jeffset** [comment]
Well, was just passing by and saw this. What you tried to do first, is to operate on "fake" (Proxy) annotation object, that KSP constructed for you. Such objects are useful to quickly access strings, ints, other stuff like that from annotations, but not classes. What happened, is classloader trying to load not-yet-compiled code, which is of course not something one should try to do. In other words, you can't use runtime reflection (`KClass` and such) for processing elements in KSP.

The approach you later discovered is indeed the correct one. Yes, the API is not that convenient for now, but asking to enhance that is more like a feature request, not a bug. No bugs here.
