### ISSUE TITLE
KSAnnotationDescriptorImpl cannot be cast to Annotation class

### ISSUE THREAD

**Issue by shubhamsinghmutualmobile** [google/ksp#891]
I have an annotation that looks like this:

```
@Retention
@Target(AnnotationTarget.FUNCTION)
annotation class Barricade(
    val endpoint: String = "",
    val responses: Array<Response> = []
)
```

Here, 'Response' is another Annotation that looks like this:

```
annotation class Response(
    val fileName: String,
    val statusCode: Int = 200,
    val type: String = "application/json",
    val isDefault: Boolean = false
)
```

I'm using them in my project like:

```
interface ApiService {
    @GET("") // This is Retrofit's GET annotation
    @Barricade(
        endpoint = "www.google.com",
        responses = [
            com.mutualmobile.barricade2.annotation.Response(fileName = "success.json", isDefault = true),
            com.mutualmobile.barricade2.annotation.Response(fileName = "failure.json"),
        ]
    )
    fun MyNetworkCall(): Response<ResponseBody> // This one is Retrofit's Response class (not my annotation class)

    @GET("")
    @Barricade(
        endpoint = "www.google1.com",
        responses = [
            com.mutualmobile.barricade2.annotation.Response(fileName = "failure.json", isDefault = true)
        ]
    )
    fun MyNewNetworkCall(): Response<ResponseBody>
}
```

My project's Visitor looks like this:
```
class BarricadeVisitor(
    private val file: OutputStream,
    private val logger: KSPLogger,
    private val annotationName: String? = Barricade::class.simpleName,
) : KSVisitorVoid() {
    override fun visitFunctionDeclaration(function: KSFunctionDeclaration, data: Unit) {
        val annotation = function.annotations.first { annotation ->
            annotation.shortName.asString() == annotationName
        }

        val endpoint = annotation.arguments.first { argument ->
            argument.name?.asString() == Barricade::endpoint.name
        }.value as String

        val responsesArgument = annotation.arguments.first { argument ->
            argument.name?.asString() == Barricade::responses.name
        }.value as ArrayList<*>

        val responses = responsesArgument.map {
            it as Response
        }

        logger.error(responses.toString())
    }
}
```

I am able to get the endpoint String successfully here ✅ but when I try to get the responsesArgument, the compiler throws this error:

```
[ksp] java.lang.ClassCastException: class com.google.devtools.ksp.symbol.impl.binary.KSAnnotationDescriptorImpl cannot be cast to class com.mutualmobile.barricade2.annotation.Response (com.google.devtools.ksp.symbol.impl.binary.KSAnnotationDescriptorImpl is in unnamed module of loader java.net.URLClassLoader @6d27a794; com.mutualmobile.barricade2.annotation.Response is in unnamed module of loader java.net.URLClassLoader @ebcf43b)
	at com.mutualmobile.compiler.visitors.BarricadeVisitor.visitFunctionDeclaration(BarricadeVisitor.kt:54)
	at com.mutualmobile.compiler.visitors.BarricadeVisitor.visitFunctionDeclaration(BarricadeVisitor.kt:12)
	at com.google.devtools.ksp.symbol.impl.kotlin.KSFunctionDeclarationImpl.accept(KSFunctionDeclarationImpl.kt:117)
	at com.mutualmobile.compiler.BarricadeProcessor.process(BarricadeProcessor.kt:44)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$4$1.invoke(KotlinSymbolProcessingExtension.kt:223)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$4$1.invoke(KotlinSymbolProcessingExtension.kt:221)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.handleException(KotlinSymbolProcessingExtension.kt:316)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.doAnalysis(KotlinSymbolProcessingExtension.kt:221)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:120)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:96)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:262)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:53)
	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:113)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:253)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:100)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:58)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:170)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:52)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:92)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:44)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:98)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1618)
	at jdk.internal.reflect.GeneratedMethodAccessor106.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)


```

My goal is to receive the ArrayList<Response> inside the visitor so that I could generate a code file which includes both the endpoint and this list of Response. Where am I going wrong?

**Comment by Anmol92verma** [comment]
Solved this using

`val responsesArgument = annotation.arguments.first { argument ->
      argument.name?.asString() == Barricade::responses.name
    }.value as ArrayList<*>
//
    responsesArgument.map {
      logger.error("found $it")
      if (it is KSAnnotation) {
        it.arguments.forEach { argument ->
          logger.error("found argument $argument")

        }
      }

    }`
