### ISSUE TITLE
NoSuchElementException when getting annotation arguments from FB's infer

### ISSUE THREAD

**Issue by amandeepg** [google/ksp#904]
If we declare a dependency on FB's [Infer](https://github.com/facebook/infer):
```groovy
api("com.facebook.infer.annotation:infer-annotation:0.18.0")
```
And declare a class using an Infer annotations:
```java
import com.facebook.infer.annotation.Nullsafe;

@Nullsafe(Nullsafe.Mode.STRICT)
public interface D {
}
```
And we try to get the information about the annotation used in the KSP processor:
```Kotlin
(resolver
  .getClassDeclarationByName("com.example.D")!!
  .annotations.first().arguments[1].value!! as KSAnnotation)
  .arguments
```

We get a `NoSuchElementException` rather than the `Set` we expect:
```
[ksp] java.util.NoSuchElementException: Collection is empty.
	at kotlin.collections.CollectionsKt___CollectionsKt.single(_Collections.kt:592)
	at com.google.devtools.ksp.symbol.impl.binary.KSAnnotationDescriptorImplKt.createKSValueArguments(KSAnnotationDescriptorImpl.kt:151)
	at com.google.devtools.ksp.symbol.impl.binary.KSAnnotationDescriptorImpl$arguments$2.invoke(KSAnnotationDescriptorImpl.kt:88)
	at com.google.devtools.ksp.symbol.impl.binary.KSAnnotationDescriptorImpl$arguments$2.invoke(KSAnnotationDescriptorImpl.kt:87)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.google.devtools.ksp.symbol.impl.binary.KSAnnotationDescriptorImpl.getArguments(KSAnnotationDescriptorImpl.kt:87)
	at TestProcessor.process(TestProcessor.kt:24)
```

Kotlin version `1.6.10`
KSP version `1.6.10-1.0.4`

**Comment by neetopia** [comment]
Can you check the classpath of the project? I've encountered this issue when trying to resolve something not on the compile time class path

**Comment by amandeepg** [comment]
I've added `api("com.facebook.infer.annotation:infer-annotation:0.18.0")` to the project's `build.gradle` and `Nullsafe` and `Nullsafe.TrustList` are both defined in `Nullsafe.java` ([on Github](https://github.com/facebook/infer/blob/main/infer/annotations/src/main/java/com/facebook/infer/annotation/Nullsafe.java)). I can upload an entire sample project if you think I'm doing something wrong with the setup

**Comment by neetopia** [comment]
Thanks, a sample project would be great

**Comment by amandeepg** [comment]
> Thanks, a sample project would be great

[playground2.zip](https://github.com/google/ksp/files/8310493/playground2.zip)

```
$ ./gradlew :workload:kspKotlin

> Task :workload:kspKotlin FAILED
e: [ksp] java.util.NoSuchElementException: Collection is empty.
        at kotlin.collections.CollectionsKt___CollectionsKt.single(_Collections.kt:592)
        at com.google.devtools.ksp.symbol.impl.binary.KSAnnotationDescriptorImplKt.createKSValueArguments(KSAnnotationDescriptorImpl.kt:151)
        at com.google.devtools.ksp.symbol.impl.binary.KSAnnotationDescriptorImpl$arguments$2.invoke(KSAnnotationDescriptorImpl.kt:88)
        at com.google.devtools.ksp.symbol.impl.binary.KSAnnotationDescriptorImpl$arguments$2.invoke(KSAnnotationDescriptorImpl.kt:87)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.google.devtools.ksp.symbol.impl.binary.KSAnnotationDescriptorImpl.getArguments(KSAnnotationDescriptorImpl.kt:87)
        at TestProcessor.process(TestProcessor.kt:14)
```

**Comment by neetopia** [comment]
It is failing resolution for nested annotation declaration `TrustList` inside the `Nullsafe` annotation, it is a bug that KSP should fix. Thanks for the reproduce project!
