### ISSUE TITLE
Incompatible with Kotlin 1.6.20

### ISSUE THREAD

**Issue by ZacSweers** [google/ksp#923]
Seeing this error when trying 1.6.20 final and using KSP `1.6.20-RC2-1.0.4`

```
e: java.lang.NoSuchMethodError: 'void org.jetbrains.kotlin.codegen.state.KotlinTypeMapper.<init>(org.jetbrains.kotlin.resolve.BindingContext, org.jetbrains.kotlin.codegen.ClassBuilderMode, java.lang.String, org.jetbrains.kotlin.config.LanguageVersionSettings, boolean, org.jetbrains.kotlin.config.JvmTarget, boolean, kotlin.jvm.functions.Function1, kotlin.jvm.functions.Function1, int, kotlin.jvm.internal.DefaultConstructorMarker)'
--
  | at com.google.devtools.ksp.processing.impl.ResolverImpl.<init>(ResolverImpl.kt:144)
  | at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.doAnalysis(KotlinSymbolProcessingExtension.kt:177)
  | at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:123)
  | at


```

**Comment by RusticFlare** [comment]
`1.6.20-1.0.4` is now out and seems to work for us

**Comment by ting-yuan** [comment]
The corresponding KSP release is published. Thanks for trying it out!
